// This file is auto-generated by scripts/generateFoodIcons.js
const foodIcons = {
  'aceituna': require('./../../icons/Vegetales/aceituna_icon.png'),
  'acelga': require('./../../icons/Vegetales/acelga_icon.png'),
  'agave': require('./../../icons/Vegetales/agave_icon.png'),
  'agua': require('./../../icons/Bebidas/agua_icon.png'),
  'aguacate': require('./../../icons/Vegetales/aguacate_icon.png'),
  'ajipicante': require('./../../icons/Vegetales/ají_picante_icon.png'),
  'ajo': require('./../../icons/Vegetales/ajo_icon.png'),
  'albahaca': require('./../../icons/Vegetales/albahaca_icon.png'),
  'alcachofa': require('./../../icons/Vegetales/alcachofa_icon.png'),
  'algasmarinas': require('./../../icons/Peces/algas_marinas_icon.png'),
  'algodon': require('./../../icons/Vegetales/algodón_icon.png'),
  'almendra': require('./../../icons/Frutas Secas/almendra_icon.png'),
  'aloevera': require('./../../icons/Vegetales/aloe_vera_icon.png'),
  'anacardo': require('./../../icons/Legumbres/anacardo_icon.png'),
  'anemonademar': require('./../../icons/Peces/anémona_de_mar_icon.png'),
  'angelote': require('./../../icons/Peces/angelote_icon.png'),
  'anguila': require('./../../icons/Peces/anguila_icon.png'),
  'apio': require('./../../icons/Vegetales/apio_icon.png'),
  'asado': require('./../../icons/Carnes/asado_icon.png'),
  'atun': require('./../../icons/Peces/atún_icon.png'),
  'avellana': require('./../../icons/Frutas Secas/avellana_icon.png'),
  'bacalao': require('./../../icons/Peces/bacalao_icon.png'),
  'ballena': require('./../../icons/Peces/ballena_icon.png'),
  'bambu': require('./../../icons/Vegetales/bambú_icon.png'),
  'banco': require('./../../icons/Peces/banco_icon.png'),
  'batata': require('./../../icons/Vegetales/batata_icon.png'),
  'batidordecocteles': require('./../../icons/Bebidas/batidor_de_coctéles_icon.png'),
  'bayas': require('./../../icons/Vegetales/bayas_icon.png'),
  'bebidaenergetica': require('./../../icons/Bebidas/bebida_energética_icon.png'),
  'bellota': require('./../../icons/Frutas Secas/bellota_icon.png'),
  'berenjenas': require('./../../icons/Vegetales/berenjenas_icon.png'),
  'blanco': require('./../../icons/Vegetales/blanco_icon.png'),
  'brocoli': require('./../../icons/Vegetales/brócoli_icon.png'),
  'caballodemar': require('./../../icons/Peces/caballo_de_mar_icon.png'),
  'cacao': require('./../../icons/Frutas Secas/cacao_icon.png'),
  'cactus': require('./../../icons/Vegetales/cactus_icon.png'),
  'cafe': require('./../../icons/Bebidas/café_icon.png'),
  'cafehelado': require('./../../icons/Bebidas/café_helado_icon.png'),
  'cajadejugo': require('./../../icons/Bebidas/caja_de_jugo_icon.png'),
  'cajadeleche': require('./../../icons/Bebidas/caja_de_leche_icon.png'),
  'calabacin': require('./../../icons/Vegetales/calabacín_icon.png'),
  'calabaza': require('./../../icons/Vegetales/calabaza_icon.png'),
  'calamar': require('./../../icons/Peces/calamar_icon.png'),
  'camaron': require('./../../icons/Peces/camarón_icon.png'),
  'canadeazucar': require('./../../icons/Vegetales/caña_de_azúcar_icon.png'),
  'canela': require('./../../icons/Vegetales/canela_icon.png'),
  'cangrejo': require('./../../icons/Peces/cangrejo_icon.png'),
  'cangrejoermitano': require('./../../icons/Peces/cangrejo_ermitaño_icon.png'),
  'capuchino': require('./../../icons/Bebidas/capuchino_icon.png'),
  'cardamomo': require('./../../icons/Frutas Secas/cardamomo_icon.png'),
  'carne': require('./../../icons/Carnes/carne_icon.png'),
  'cascara': require('./../../icons/Peces/cáscara_icon.png'),
  'castana': require('./../../icons/Frutas Secas/castaña_icon.png'),
  'caucho': require('./../../icons/Vegetales/caucho_icon.png'),
  'cebolla': require('./../../icons/Vegetales/cebolla_icon.png'),
  'cebollin': require('./../../icons/Vegetales/cebollín_icon.png'),
  'cerdo': require('./../../icons/Carnes/cerdo_icon.png'),
  'cereza': require('./../../icons/Frutas/cereza_icon.png'),
  'cerveza': require('./../../icons/Bebidas/cerveza_icon.png'),
  'chalote': require('./../../icons/Vegetales/chalote_icon.png'),
  'champan': require('./../../icons/Bebidas/champán_icon.png'),
  'chia': require('./../../icons/Legumbres/chía_icon.png'),
  'chocolatecaliente': require('./../../icons/Bebidas/chocolate_caliente_icon.png'),
  'clavo': require('./../../icons/Vegetales/clavo_icon.png'),
  'coco': require('./../../icons/Bebidas/coco_icon.png'),
  'coctel': require('./../../icons/Bebidas/cóctel_icon.png'),
  'coliflor': require('./../../icons/Vegetales/coliflor_icon.png'),
  'colrizada': require('./../../icons/Vegetales/col_rizada_icon.png'),
  'concha': require('./../../icons/Peces/concha_icon.png'),
  'conodepino': require('./../../icons/Frutas Secas/cono_de_pino_icon.png'),
  'coral': require('./../../icons/Peces/coral_icon.png'),
  'cordero': require('./../../icons/Carnes/cordero_icon.png'),
  'cosmopolita': require('./../../icons/Bebidas/cosmopolita_icon.png'),
  'costillas': require('./../../icons/Carnes/costillas_icon.png'),
  'dalgona': require('./../../icons/Bebidas/dalgona_icon.png'),
  'delfin': require('./../../icons/Peces/delfín_icon.png'),
  'dragondefruta': require('./../../icons/Frutas/dragon_de_fruta_icon.png'),
  'durian': require('./../../icons/Frutas/durian_icon.png'),
  'edamame': require('./../../icons/Legumbres/edamame_icon.png'),
  'erizodemar': require('./../../icons/Peces/erizo_de_mar_icon.png'),
  'esparragos': require('./../../icons/Vegetales/espárragos_icon.png'),
  'espina': require('./../../icons/Peces/espina_icon.png'),
  'espinacas': require('./../../icons/Vegetales/espinacas_icon.png'),
  'estrellademar': require('./../../icons/Peces/estrella_de_mar_icon.png'),
  'ficus': require('./../../icons/Frutas/ficus_icon.png'),
  'filete': require('./../../icons/Carnes/filete_icon.png'),
  'frambuesa': require('./../../icons/Frutas/frambuesa_icon.png'),
  'fresa': require('./../../icons/Frutas/fresa_icon.png'),
  'frijoles': require('./../../icons/Legumbres/frijoles_icon.png'),
  'frijolesrojos': require('./../../icons/Legumbres/frijoles_rojos_icon.png'),
  'fruta': require('./../../icons/Vegetales/fruta_icon.png'),
  'frutaestrella': require('./../../icons/Vegetales/fruta_estrella_icon.png'),
  'garbanzos': require('./../../icons/Legumbres/garbanzos_icon.png'),
  'gaviota': require('./../../icons/Peces/gaviota_icon.png'),
  'girasol': require('./../../icons/Vegetales/girasol_icon.png'),
  'goji': require('./../../icons/Vegetales/goji_icon.png'),
  'granada': require('./../../icons/Vegetales/granada_icon.png'),
  'granosdecafe': require('./../../icons/Frutas Secas/granos_de_café_icon.png'),
  'guisantes': require('./../../icons/Legumbres/guisantes_icon.png'),
  'habadesoja': require('./../../icons/Legumbres/haba_de_soja_icon.png'),
  'hamburguesa': require('./../../icons/Carnes/hamburguesa_icon.png'),
  'hierba': require('./../../icons/Vegetales/hierba_icon.png'),
  'higado': require('./../../icons/Carnes/hígado_icon.png'),
  'hinojo': require('./../../icons/Vegetales/hinojo_icon.png'),
  'horchata': require('./../../icons/Bebidas/horchata_icon.png'),
  'idolomoro': require('./../../icons/Peces/Ídolo_moro_icon.png'),
  'infusion': require('./../../icons/Bebidas/infusión_icon.png'),
  'jengibre': require('./../../icons/Vegetales/jengibre_icon.png'),
  'judiasverdes': require('./../../icons/Legumbres/judías_verdes_icon.png'),
  'kiwi': require('./../../icons/Vegetales/kiwi_icon.png'),
  'kombucha': require('./../../icons/Bebidas/kombucha_icon.png'),
  'langosta': require('./../../icons/Peces/langosta_icon.png'),
  'lata': require('./../../icons/Carnes/lata_icon.png'),
  'lattemacchiato': require('./../../icons/Bebidas/latte_macchiato_icon.png'),
  'leche': require('./../../icons/Bebidas/leche_icon.png'),
  'lecheconchocolate': require('./../../icons/Bebidas/leche_con_chocolate_icon.png'),
  'lechedefresa': require('./../../icons/Bebidas/leche_de_fresa_icon.png'),
  'lechuga': require('./../../icons/Vegetales/lechuga_icon.png'),
  'lentejas': require('./../../icons/Legumbres/lentejas_icon.png'),
  'lima': require('./../../icons/Vegetales/lima_icon.png'),
  'limon': require('./../../icons/Vegetales/limón_icon.png'),
  'limonada': require('./../../icons/Bebidas/limonada_icon.png'),
  'lychee': require('./../../icons/Vegetales/lychee_icon.png'),
  'macadamia': require('./../../icons/Frutas Secas/macadamia_icon.png'),
  'maiz': require('./../../icons/Legumbres/maíz_icon.png'),
  'malteada': require('./../../icons/Bebidas/malteada_icon.png'),
  'mango': require('./../../icons/Frutas/mango_icon.png'),
  'mangostan': require('./../../icons/Vegetales/mangostán_icon.png'),
  'mani': require('./../../icons/Frutas Secas/maní_icon.png'),
  'manzana': require('./../../icons/Frutas/manzana_icon.png'),
  'manzanarosa': require('./../../icons/Vegetales/manzana_rosa_icon.png'),
  'maracuya': require('./../../icons/Vegetales/maracuyá_icon.png'),
  'margarita': require('./../../icons/Bebidas/margarita_icon.png'),
  'martini': require('./../../icons/Bebidas/martini_icon.png'),
  'matcha': require('./../../icons/Bebidas/matcha_icon.png'),
  'medusa': require('./../../icons/Peces/medusa_icon.png'),
  'mejillon': require('./../../icons/Peces/mejillón_icon.png'),
  'melocoton': require('./../../icons/Frutas/melocotón_icon.png'),
  'melon': require('./../../icons/Frutas/melón_icon.png'),
  'membrillo': require('./../../icons/Vegetales/membrillo_icon.png'),
  'mimosa': require('./../../icons/Bebidas/mimosa_icon.png'),
  'mojito': require('./../../icons/Bebidas/mojito_icon.png'),
  'nabo': require('./../../icons/Vegetales/nabo_icon.png'),
  'naranja': require('./../../icons/Frutas/naranja_icon.png'),
  'natillasappel': require('./../../icons/Vegetales/natillas_appel_icon.png'),
  'nuecesdebrasil': require('./../../icons/Frutas Secas/nueces_de_brasil_icon.png'),
  'nuez': require('./../../icons/Frutas Secas/nuez_icon.png'),
  'nuezmoscada': require('./../../icons/Frutas Secas/nuez_moscada_icon.png'),
  'orca': require('./../../icons/Peces/orca_icon.png'),
  'pacana': require('./../../icons/Frutas Secas/pacana_icon.png'),
  'palillodetambor': require('./../../icons/Carnes/palillo_de_tambor_icon.png'),
  'palmeradatilera': require('./../../icons/Vegetales/palmera_datilera_icon.png'),
  'papaya': require('./../../icons/Frutas/papaya_icon.png'),
  'patatas': require('./../../icons/Vegetales/patatas_icon.png'),
  'pepino': require('./../../icons/Vegetales/pepino_icon.png'),
  'pera': require('./../../icons/Frutas/pera_icon.png'),
  'pez': require('./../../icons/Carnes/pez_icon.png'),
  'pezcirujano': require('./../../icons/Peces/pez_cirujano_icon.png'),
  'pezespada': require('./../../icons/Peces/pez_espada_icon.png'),
  'pezglobo': require('./../../icons/Peces/pez_globo_icon.png'),
  'pezluna': require('./../../icons/Peces/pez_luna_icon.png'),
  'pezmartillo': require('./../../icons/Peces/pez_martillo_icon.png'),
  'pezpayaso': require('./../../icons/Peces/pez_payaso_icon.png'),
  'pezvolador': require('./../../icons/Peces/pez_volador_icon.png'),
  'physalis': require('./../../icons/Vegetales/physalis_icon.png'),
  'pimienta': require('./../../icons/Vegetales/pimienta_icon.png'),
  'pina': require('./../../icons/Frutas/piña_icon.png'),
  'pistacho': require('./../../icons/Frutas Secas/pistacho_icon.png'),
  'platano': require('./../../icons/Frutas/plátano_icon.png'),
  'pollo': require('./../../icons/Carnes/pollo_icon.png'),
  'puerro': require('./../../icons/Vegetales/puerro_icon.png'),
  'pulpo': require('./../../icons/Peces/pulpo_icon.png'),
  'punetazo': require('./../../icons/Bebidas/puñetazo_icon.png'),
  'rabano': require('./../../icons/Vegetales/rábano_icon.png'),
  'ramune': require('./../../icons/Bebidas/ramune_icon.png'),
  'rape': require('./../../icons/Peces/rape_icon.png'),
  'rayo': require('./../../icons/Peces/rayo_icon.png'),
  'reajustesalarial': require('./../../icons/Bebidas/reajuste_salarial_icon.png'),
  'remolacha': require('./../../icons/Vegetales/remolacha_icon.png'),
  'repollo': require('./../../icons/Vegetales/repollo_icon.png'),
  'repollorojo': require('./../../icons/Vegetales/repollo_rojo_icon.png'),
  'rinon': require('./../../icons/Carnes/riñón_icon.png'),
  'salami': require('./../../icons/Carnes/salami_icon.png'),
  'salchicha': require('./../../icons/Carnes/salchicha_icon.png'),
  'salmon': require('./../../icons/Carnes/salmón_icon.png'),
  'sandia': require('./../../icons/Frutas/sandía_icon.png'),
  'sangria': require('./../../icons/Bebidas/sangría_icon.png'),
  'sardina': require('./../../icons/Peces/sardina_icon.png'),
  'semilladecalabaza': require('./../../icons/Frutas Secas/semilla_de_calabaza_icon.png'),
  'semilladegirasol': require('./../../icons/Frutas Secas/semilla_de_girasol_icon.png'),
  'semilladelino': require('./../../icons/Frutas Secas/semilla_de_lino_icon.png'),
  'serpientedemar': require('./../../icons/Peces/serpiente_de_mar_icon.png'),
  'sesamo': require('./../../icons/Frutas Secas/sésamo_icon.png'),
  'seta': require('./../../icons/Vegetales/seta_icon.png'),
  'soda': require('./../../icons/Bebidas/soda_icon.png'),
  'sodaconhelado': require('./../../icons/Bebidas/soda_con_helado_icon.png'),
  'tamarindo': require('./../../icons/Vegetales/tamarindo_icon.png'),
  'te': require('./../../icons/Bebidas/té_icon.png'),
  'tedeburbujas': require('./../../icons/Bebidas/té_de_burbujas_icon.png'),
  'tehelado': require('./../../icons/Bebidas/té_helado_icon.png'),
  'tetera': require('./../../icons/Bebidas/tetera_icon.png'),
  'tiburon': require('./../../icons/Peces/tiburón_icon.png'),
  'tomate': require('./../../icons/Vegetales/tomate_icon.png'),
  'tortuga': require('./../../icons/Peces/tortuga_icon.png'),
  'trigo': require('./../../icons/Vegetales/trigo_icon.png'),
  'uva': require('./../../icons/Frutas/uva_icon.png'),
  'vegetal': require('./../../icons/Vegetales/vegetal_icon.png'),
  'vino': require('./../../icons/Bebidas/vino_icon.png'),
  'wasabi': require('./../../icons/Vegetales/wasabi_icon.png'),
  'whisky': require('./../../icons/Bebidas/whisky_icon.png'),
  'zalamero': require('./../../icons/Bebidas/zalamero_icon.png'),
  'zanahoria': require('./../../icons/Vegetales/zanahoria_icon.png'),
  'zumodenaranja': require('./../../icons/Bebidas/zumo_de_naranja_icon.png'),
};

export const categories = {
  'bebidas': {
    icon: require('./../../icons/Categorias/Bebidas.png'),
    items: ['agua', 'batidordecocteles', 'bebidaenergetica', 'cafe', 'cafehelado', 'cajadejugo', 'cajadeleche', 'capuchino', 'cerveza', 'champan', 'chocolatecaliente', 'coco', 'coctel', 'cosmopolita', 'dalgona', 'horchata', 'infusion', 'kombucha', 'lattemacchiato', 'leche', 'lecheconchocolate', 'lechedefresa', 'limonada', 'malteada', 'margarita', 'martini', 'matcha', 'mimosa', 'mojito', 'punetazo', 'ramune', 'reajustesalarial', 'sangria', 'soda', 'sodaconhelado', 'te', 'tedeburbujas', 'tehelado', 'tetera', 'vino', 'whisky', 'zalamero', 'zumodenaranja'],
  },
  'carnes': {
    icon: require('./../../icons/Categorias/Carnes.png'),
    items: ['asado', 'carne', 'cerdo', 'cordero', 'costillas', 'filete', 'hamburguesa', 'higado', 'lata', 'palillodetambor', 'pez', 'pollo', 'rinon', 'salami', 'salchicha', 'salmon'],
  },
  'cereales': {
    icon: require('./../../icons/Categorias/Cereales.png'),
    items: [],
  },
  'frutas': {
    icon: require('./../../icons/Categorias/Frutas.png'),
    items: ['cereza', 'coco', 'dragondefruta', 'durian', 'ficus', 'frambuesa', 'fresa', 'mango', 'manzana', 'melocoton', 'melon', 'naranja', 'papaya', 'pera', 'pina', 'platano', 'sandia', 'uva'],
  },
  'frutassecas': {
    icon: require('./../../icons/Categorias/Frutas Secas.png'),
    items: ['almendra', 'avellana', 'bellota', 'cacao', 'cardamomo', 'castana', 'coco', 'conodepino', 'granosdecafe', 'macadamia', 'mani', 'nuecesdebrasil', 'nuez', 'nuezmoscada', 'pacana', 'pistacho', 'semilladecalabaza', 'semilladegirasol', 'semilladelino', 'sesamo'],
  },
  'legumbres': {
    icon: require('./../../icons/Categorias/Legumbres.png'),
    items: ['anacardo', 'chia', 'edamame', 'frijoles', 'frijolesrojos', 'garbanzos', 'guisantes', 'habadesoja', 'judiasverdes', 'lentejas', 'maiz'],
  },
  'peces': {
    icon: require('./../../icons/Categorias/Peces.png'),
    items: ['algasmarinas', 'anemonademar', 'angelote', 'anguila', 'atun', 'bacalao', 'ballena', 'banco', 'caballodemar', 'calamar', 'camaron', 'cangrejo', 'cangrejoermitano', 'cascara', 'concha', 'coral', 'delfin', 'erizodemar', 'espina', 'estrellademar', 'gaviota', 'idolomoro', 'langosta', 'medusa', 'mejillon', 'orca', 'pez', 'pezcirujano', 'pezespada', 'pezglobo', 'pezluna', 'pezmartillo', 'pezpayaso', 'pezvolador', 'pulpo', 'rape', 'rayo', 'sardina', 'serpientedemar', 'tiburon', 'tortuga'],
  },
  'vegetales': {
    icon: require('./../../icons/Categorias/Vegetales.png'),
    items: ['aceituna', 'acelga', 'agave', 'aguacate', 'ajipicante', 'ajo', 'albahaca', 'alcachofa', 'algodon', 'almendra', 'aloevera', 'apio', 'bambu', 'batata', 'bayas', 'berenjenas', 'blanco', 'brocoli', 'cacao', 'cactus', 'cafe', 'calabacin', 'calabaza', 'canadeazucar', 'canela', 'caucho', 'cebolla', 'cebollin', 'chalote', 'clavo', 'coliflor', 'colrizada', 'esparragos', 'espinacas', 'frijoles', 'fruta', 'frutaestrella', 'girasol', 'goji', 'granada', 'habadesoja', 'hierba', 'hinojo', 'jengibre', 'kiwi', 'lechuga', 'lima', 'limon', 'lychee', 'maiz', 'mangostan', 'mani', 'manzanarosa', 'maracuya', 'membrillo', 'nabo', 'natillasappel', 'nuez', 'pacana', 'palmeradatilera', 'patatas', 'pepino', 'physalis', 'pimienta', 'puerro', 'rabano', 'remolacha', 'repollo', 'repollorojo', 'seta', 'tamarindo', 'tomate', 'trigo', 'vegetal', 'wasabi', 'zanahoria'],
  },
};

export const expirationDays = {
  'frijoles': 365,
  'guisantes': 180,
  'lentejas': 365,
  'maiz': 365,
  'manzana': 30,
  'tomate': 7,
  'zanahoria': 14,
};

let customIconMap = {};
let customCategoryMap = {};
let customExpirationMap = {};

export function setCustomFoodsMap(foods) {
  customIconMap = {};
  customCategoryMap = {};
  customExpirationMap = {};
  foods.forEach(f => {
    customCategoryMap[f.key] = f.category;
    if (f.icon) {
      customIconMap[f.key] = { uri: f.icon };
    } else if (f.baseIcon) {
      const baseKey = normalizeFoodName(f.baseIcon);
      customIconMap[f.key] = foodIcons[baseKey];
    }
    if (f.expiresIn) {
      customExpirationMap[f.key] = f.expiresIn;
    }
  });
}

export function normalizeFoodName(name) {
  return name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, '');
}

export function getFoodIcon(name) {
  const key = normalizeFoodName(name);
  return customIconMap[key] || foodIcons[key];
}

export function getFoodCategory(name) {
  const normalized = normalizeFoodName(name);
  if (customCategoryMap[normalized]) return customCategoryMap[normalized];
  for (const [cat, data] of Object.entries(categories)) {
    if (data.items.includes(normalized)) {
      return cat;
    }
  }
  return null;
}

export function getDefaultExpiration(name, fromDate = new Date()) {
  const key = normalizeFoodName(name);
  const days = customExpirationMap[key] ?? expirationDays[key];
  if (!days) return '';
  const base = new Date(fromDate);
  base.setDate(base.getDate() + days);
  return base.toISOString().split('T')[0];
}

export default foodIcons;
