// This file is auto-generated by scripts/generateFoodIcons.js
export const foodData = {
  'aceitedeoliva': {
    icon: require('./../../icons/Comidas/aceite_de_oliva_icon.png'),
    name: 'Aceite De Oliva',
    expirationDays: null,
  },
  'aceitevegetal': {
    icon: require('./../../icons/Condimentos/aceite_vegetal_icon.png'),
    name: 'Aceite Vegetal',
    expirationDays: null,
  },
  'aceituna': {
    icon: require('./../../icons/Vegetales/aceituna_icon.png'),
    name: 'Aceituna',
    expirationDays: null,
  },
  'acelga': {
    icon: require('./../../icons/Vegetales/acelga_icon.png'),
    name: 'Acelga',
    expirationDays: null,
  },
  'agave': {
    icon: require('./../../icons/Vegetales/agave_icon.png'),
    name: 'Agave',
    expirationDays: null,
  },
  'agua': {
    icon: require('./../../icons/Bebidas/agua_icon.png'),
    name: 'Agua',
    expirationDays: null,
  },
  'aguacate': {
    icon: require('./../../icons/Vegetales/aguacate_icon.png'),
    name: 'Aguacate',
    expirationDays: null,
  },
  'aguamineral': {
    icon: require('./../../icons/Bebidas/agua_mineral_icon.png'),
    name: 'Agua Mineral',
    expirationDays: null,
  },
  'ajipicante': {
    icon: require('./../../icons/Vegetales/ají_picante_icon.png'),
    name: 'Ají Picante',
    expirationDays: null,
  },
  'ajo': {
    icon: require('./../../icons/Condimentos/ajo_icon.png'),
    name: 'Ajo',
    expirationDays: null,
  },
  'albahaca': {
    icon: require('./../../icons/Condimentos/albahaca_icon.png'),
    name: 'Albahaca',
    expirationDays: null,
  },
  'albondigas': {
    icon: require('./../../icons/Carnes/albóndigas_icon.png'),
    name: 'Albóndigas',
    expirationDays: null,
  },
  'alcachofa': {
    icon: require('./../../icons/Comidas/alcachofa_icon.png'),
    name: 'Alcachofa',
    expirationDays: null,
  },
  'alcaravea': {
    icon: require('./../../icons/Condimentos/alcaravea_icon.png'),
    name: 'Alcaravea',
    expirationDays: null,
  },
  'algasmarinas': {
    icon: require('./../../icons/Peces/algas_marinas_icon.png'),
    name: 'Algas Marinas',
    expirationDays: null,
  },
  'algodondeazucar': {
    icon: require('./../../icons/Dulces/algodón_de_azúcar_icon.png'),
    name: 'Algodón De Azúcar',
    expirationDays: null,
  },
  'alitadepollo': {
    icon: require('./../../icons/Carnes/alita_de_pollo_icon_5.png'),
    name: 'Alita De Pollo',
    expirationDays: null,
  },
  'alitasdepollo': {
    icon: require('./../../icons/Carnes/Alitas_de_pollo_icon_4.png'),
    name: 'Alitas De Pollo',
    expirationDays: null,
  },
  'almendra': {
    icon: require('./../../icons/Comidas/Almendra_icon.png'),
    name: 'Almendra',
    expirationDays: null,
  },
  'anacardo': {
    icon: require('./../../icons/Legumbres/anacardo_icon.png'),
    name: 'Anacardo',
    expirationDays: null,
  },
  'anemonademar': {
    icon: require('./../../icons/Peces/anémona_de_mar_icon.png'),
    name: 'Anémona De Mar',
    expirationDays: null,
  },
  'angelote': {
    icon: require('./../../icons/Peces/angelote_icon.png'),
    name: 'Angelote',
    expirationDays: null,
  },
  'anguila': {
    icon: require('./../../icons/Peces/anguila_icon.png'),
    name: 'Anguila',
    expirationDays: null,
  },
  'anillopop': {
    icon: require('./../../icons/Dulces/anillo_pop_icon.png'),
    name: 'Anillo Pop',
    expirationDays: null,
  },
  'anis': {
    icon: require('./../../icons/Condimentos/anís_icon.png'),
    name: 'Anís',
    expirationDays: null,
  },
  'apio': {
    icon: require('./../../icons/Vegetales/apio_icon.png'),
    name: 'Apio',
    expirationDays: null,
  },
  'arce': {
    icon: require('./../../icons/Variado/arce_icon.png'),
    name: 'Arce',
    expirationDays: null,
  },
  'arcoiris': {
    icon: require('./../../icons/Bebidas/arco_iris_icon.png'),
    name: 'Arco Iris',
    expirationDays: null,
  },
  'arroz': {
    icon: require('./../../icons/Comidas/arroz_icon.png'),
    name: 'Arroz',
    expirationDays: null,
  },
  'asado': {
    icon: require('./../../icons/Carnes/asado_icon.png'),
    name: 'Asado',
    expirationDays: null,
  },
  'atun': {
    icon: require('./../../icons/Peces/atún_icon.png'),
    name: 'Atún',
    expirationDays: null,
  },
  'avellana': {
    icon: require('./../../icons/Frutas Secas/avellana_icon.png'),
    name: 'Avellana',
    expirationDays: null,
  },
  'ayran': {
    icon: require('./../../icons/Bebidas/ayran_icon.png'),
    name: 'Ayran',
    expirationDays: null,
  },
  'azafran': {
    icon: require('./../../icons/Condimentos/azafrán_icon.png'),
    name: 'Azafrán',
    expirationDays: null,
  },
  'azucar': {
    icon: require('./../../icons/Condimentos/azúcar_icon.png'),
    name: 'Azúcar',
    expirationDays: null,
  },
  'bacalao': {
    icon: require('./../../icons/Peces/bacalao_icon.png'),
    name: 'Bacalao',
    expirationDays: null,
  },
  'ballena': {
    icon: require('./../../icons/Peces/ballena_icon.png'),
    name: 'Ballena',
    expirationDays: null,
  },
  'bambu': {
    icon: require('./../../icons/Vegetales/bambú_icon.png'),
    name: 'Bambú',
    expirationDays: null,
  },
  'banco': {
    icon: require('./../../icons/Peces/banco_icon.png'),
    name: 'Banco',
    expirationDays: null,
  },
  'barbacoa': {
    icon: require('./../../icons/Comidas/barbacoa_icon.png'),
    name: 'Barbacoa',
    expirationDays: null,
  },
  'barradechocolate': {
    icon: require('./../../icons/Dulces/barra_de_chocolate_icon.png'),
    name: 'Barra De Chocolate',
    expirationDays: null,
  },
  'bastondecaramelo': {
    icon: require('./../../icons/Dulces/bastón_de_caramelo_icon.png'),
    name: 'Bastón De Caramelo',
    expirationDays: null,
  },
  'batata': {
    icon: require('./../../icons/Vegetales/batata_icon.png'),
    name: 'Batata',
    expirationDays: null,
  },
  'batidordecocteles': {
    icon: require('./../../icons/Bebidas/batidor_de_coctéles_icon.png'),
    name: 'Batidor De Coctéles',
    expirationDays: null,
  },
  'batidos': {
    icon: require('./../../icons/Comidas/batidos_icon.png'),
    name: 'Batidos',
    expirationDays: null,
  },
  'bayadeespino': {
    icon: require('./../../icons/Condimentos/baya_de_espino_icon.png'),
    name: 'Baya De Espino',
    expirationDays: null,
  },
  'bayas': {
    icon: require('./../../icons/Condimentos/bayas_icon.png'),
    name: 'Bayas',
    expirationDays: null,
  },
  'beber': {
    icon: require('./../../icons/Bebidas/beber_icon.png'),
    name: 'Beber',
    expirationDays: null,
  },
  'bebidacaliente': {
    icon: require('./../../icons/Variado/bebida_caliente_icon.png'),
    name: 'Bebida Caliente',
    expirationDays: null,
  },
  'bebidadecoco': {
    icon: require('./../../icons/Bebidas/bebida_de_coco_icon.png'),
    name: 'Bebida De Coco',
    expirationDays: null,
  },
  'bebidaenergetica': {
    icon: require('./../../icons/Bebidas/bebida_energética_icon.png'),
    name: 'Bebida Energética',
    expirationDays: null,
  },
  'bebidassinalcohol': {
    icon: require('./../../icons/Bebidas/bebidas_sin_alcohol_icon.png'),
    name: 'Bebidas Sin Alcohol',
    expirationDays: null,
  },
  'bellota': {
    icon: require('./../../icons/Frutas Secas/bellota_icon.png'),
    name: 'Bellota',
    expirationDays: null,
  },
  'berbero': {
    icon: require('./../../icons/Condimentos/bérbero_icon.png'),
    name: 'Bérbero',
    expirationDays: null,
  },
  'berenjena': {
    icon: require('./../../icons/Comidas/berenjena_icon.png'),
    name: 'Berenjena',
    expirationDays: null,
  },
  'berenjenas': {
    icon: require('./../../icons/Vegetales/berenjenas_icon.png'),
    name: 'Berenjenas',
    expirationDays: null,
  },
  'berro': {
    icon: require('./../../icons/Condimentos/berro_icon.png'),
    name: 'Berro',
    expirationDays: null,
  },
  'bife': {
    icon: require('./../../icons/Carnes/bife_icon.png'),
    name: 'Bife',
    expirationDays: null,
  },
  'bistec': {
    icon: require('./../../icons/Carnes/bistec_icon.png'),
    name: 'Bistec',
    expirationDays: null,
  },
  'bloodymary': {
    icon: require('./../../icons/Bebidas/bloody_mary_icon.png'),
    name: 'Bloody Mary',
    expirationDays: null,
  },
  'bocadillo': {
    icon: require('./../../icons/Comidas/bocadillo_icon.png'),
    name: 'Bocadillo',
    expirationDays: null,
  },
  'bolasdechoco': {
    icon: require('./../../icons/Dulces/bolas_de_choco_icon.png'),
    name: 'Bolas De Choco',
    expirationDays: null,
  },
  'bollo': {
    icon: require('./../../icons/Panes/bollo_icon.png'),
    name: 'Bollo',
    expirationDays: null,
  },
  'borbon': {
    icon: require('./../../icons/Bebidas/borbón_icon.png'),
    name: 'Borbón',
    expirationDays: null,
  },
  'brocheta': {
    icon: require('./../../icons/Comidas/brocheta_icon.png'),
    name: 'Brocheta',
    expirationDays: null,
  },
  'brocoli': {
    icon: require('./../../icons/Comidas/Brócoli_icon.png'),
    name: 'Brócoli',
    expirationDays: null,
  },
  'burbujas': {
    icon: require('./../../icons/Peces/burbujas_icon.png'),
    name: 'Burbujas',
    expirationDays: null,
  },
  'burrito': {
    icon: require('./../../icons/Comidas/burrito_icon.png'),
    name: 'Burrito',
    expirationDays: null,
  },
  'caballodemar': {
    icon: require('./../../icons/Peces/caballo_de_mar_icon.png'),
    name: 'Caballo De Mar',
    expirationDays: null,
  },
  'cacao': {
    icon: require('./../../icons/Dulces/cacao_icon.png'),
    name: 'Cacao',
    expirationDays: null,
  },
  'cafe': {
    icon: require('./../../icons/Bebidas/café_icon.png'),
    name: 'Café',
    expirationDays: null,
  },
  'cafehelado': {
    icon: require('./../../icons/Bebidas/café_helado_icon.png'),
    name: 'Café Helado',
    expirationDays: null,
  },
  'cafeturco': {
    icon: require('./../../icons/Bebidas/café_turco_icon.png'),
    name: 'Café Turco',
    expirationDays: null,
  },
  'cajadejugo': {
    icon: require('./../../icons/Bebidas/caja_de_jugo_icon.png'),
    name: 'Caja De Jugo',
    expirationDays: null,
  },
  'cajadeleche': {
    icon: require('./../../icons/Bebidas/caja_de_leche_icon.png'),
    name: 'Caja De Leche',
    expirationDays: null,
  },
  'cal': {
    icon: require('./../../icons/Condimentos/cal_icon.png'),
    name: 'Cal',
    expirationDays: null,
  },
  'calabaza': {
    icon: require('./../../icons/Vegetales/calabaza_icon.png'),
    name: 'Calabaza',
    expirationDays: null,
  },
  'calamar': {
    icon: require('./../../icons/Peces/calamar_icon.png'),
    name: 'Calamar',
    expirationDays: null,
  },
  'calendario': {
    icon: require('./../../icons/Carnes/calendario_icon.png'),
    name: 'Calendario',
    expirationDays: null,
  },
  'camaron': {
    icon: require('./../../icons/Comidas/camarón_icon.png'),
    name: 'Camarón',
    expirationDays: null,
  },
  'canela': {
    icon: require('./../../icons/Condimentos/canela_icon.png'),
    name: 'Canela',
    expirationDays: null,
  },
  'cangrejo': {
    icon: require('./../../icons/Comidas/cangrejo_icon.png'),
    name: 'Cangrejo',
    expirationDays: null,
  },
  'cangrejoermitano': {
    icon: require('./../../icons/Peces/cangrejo_ermitaño_icon.png'),
    name: 'Cangrejo Ermitaño',
    expirationDays: null,
  },
  'cannoli': {
    icon: require('./../../icons/Comidas/cannoli_icon.png'),
    name: 'Cannoli',
    expirationDays: null,
  },
  'capuchino': {
    icon: require('./../../icons/Bebidas/capuchino_icon.png'),
    name: 'Capuchino',
    expirationDays: null,
  },
  'caramelo': {
    icon: require('./../../icons/Comidas/caramelo_icon.png'),
    name: 'Caramelo',
    expirationDays: null,
  },
  'cardamomo': {
    icon: require('./../../icons/Condimentos/cardamomo_icon.png'),
    name: 'Cardamomo',
    expirationDays: null,
  },
  'carino': {
    icon: require('./../../icons/Dulces/cariño_icon.png'),
    name: 'Cariño',
    expirationDays: null,
  },
  'carne': {
    icon: require('./../../icons/Carnes/carne_icon.png'),
    name: 'Carne',
    expirationDays: null,
  },
  'carnedecordero': {
    icon: require('./../../icons/Carnes/carne_de_cordero_icon.png'),
    name: 'Carne De Cordero',
    expirationDays: null,
  },
  'carnedevaca': {
    icon: require('./../../icons/Carnes/carne_de_vaca_icon.png'),
    name: 'Carne De Vaca',
    expirationDays: null,
  },
  'carnemolida': {
    icon: require('./../../icons/Carnes/carne_molida_icon.png'),
    name: 'Carne Molida',
    expirationDays: null,
  },
  'carniceria': {
    icon: require('./../../icons/Carnes/carnicería_icon.png'),
    name: 'Carnicería',
    expirationDays: null,
  },
  'cascara': {
    icon: require('./../../icons/Peces/cáscara_icon.png'),
    name: 'Cáscara',
    expirationDays: null,
  },
  'castana': {
    icon: require('./../../icons/Frutas Secas/castaña_icon.png'),
    name: 'Castaña',
    expirationDays: null,
  },
  'ccreaagria': {
    icon: require('./../../icons/Lácteos/ccrea_agria_icon.png'),
    name: 'Ccrea Agria',
    expirationDays: null,
  },
  'cebolla': {
    icon: require('./../../icons/Comidas/cebolla_icon.png'),
    name: 'Cebolla',
    expirationDays: null,
  },
  'cebollaverde': {
    icon: require('./../../icons/Condimentos/cebolla_verde_icon.png'),
    name: 'Cebolla Verde',
    expirationDays: null,
  },
  'cebollin': {
    icon: require('./../../icons/Vegetales/cebollín_icon.png'),
    name: 'Cebollín',
    expirationDays: null,
  },
  'cena': {
    icon: require('./../../icons/Comidas/Cena_icon.png'),
    name: 'Cena',
    expirationDays: null,
  },
  'cerdo': {
    icon: require('./../../icons/Carnes/cerdo_icon.png'),
    name: 'Cerdo',
    expirationDays: null,
  },
  'cereal': {
    icon: require('./../../icons/Cereales/cereal_icon.png'),
    name: 'Cereal',
    expirationDays: null,
  },
  'cereales': {
    icon: require('./../../icons/Comidas/cereales_icon.png'),
    name: 'Cereales',
    expirationDays: null,
  },
  'cereza': {
    icon: require('./../../icons/Frutas/cereza_icon.png'),
    name: 'Cereza',
    expirationDays: null,
  },
  'cerveza': {
    icon: require('./../../icons/Bebidas/cerveza_icon.png'),
    name: 'Cerveza',
    expirationDays: null,
  },
  'cesta': {
    icon: require('./../../icons/Panes/cesta_icon.png'),
    name: 'Cesta',
    expirationDays: null,
  },
  'chalote': {
    icon: require('./../../icons/Vegetales/chalote_icon.png'),
    name: 'Chalote',
    expirationDays: null,
  },
  'champan': {
    icon: require('./../../icons/Bebidas/champán_icon.png'),
    name: 'Champán',
    expirationDays: null,
  },
  'chia': {
    icon: require('./../../icons/Legumbres/chía_icon.png'),
    name: 'Chía',
    expirationDays: null,
  },
  'chicle': {
    icon: require('./../../icons/Dulces/chicle_icon.png'),
    name: 'Chicle',
    expirationDays: null,
  },
  'chicles': {
    icon: require('./../../icons/Dulces/chicles_icon.png'),
    name: 'Chicles',
    expirationDays: null,
  },
  'chile': {
    icon: require('./../../icons/Condimentos/chile_icon.png'),
    name: 'Chile',
    expirationDays: null,
  },
  'chocolate': {
    icon: require('./../../icons/Comidas/Chocolate_icon.png'),
    name: 'Chocolate',
    expirationDays: null,
  },
  'chocolatecaliente': {
    icon: require('./../../icons/Bebidas/chocolate_caliente_icon.png'),
    name: 'Chocolate Caliente',
    expirationDays: null,
  },
  'chuleta': {
    icon: require('./../../icons/Carnes/chuleta_icon.png'),
    name: 'Chuleta',
    expirationDays: null,
  },
  'chupete': {
    icon: require('./../../icons/Comidas/chupete_icon.png'),
    name: 'Chupete',
    expirationDays: null,
  },
  'churros': {
    icon: require('./../../icons/Dulces/churros_icon.png'),
    name: 'Churros',
    expirationDays: null,
  },
  'cilantro': {
    icon: require('./../../icons/Condimentos/cilantro_icon.png'),
    name: 'Cilantro',
    expirationDays: null,
  },
  'clavo': {
    icon: require('./../../icons/Condimentos/clavo_icon.png'),
    name: 'Clavo',
    expirationDays: null,
  },
  'coco': {
    icon: require('./../../icons/Bebidas/coco_icon.png'),
    name: 'Coco',
    expirationDays: null,
  },
  'coctel': {
    icon: require('./../../icons/Bebidas/cóctel_icon.png'),
    name: 'Cóctel',
    expirationDays: null,
  },
  'col': {
    icon: require('./../../icons/Comidas/Col_icon.png'),
    name: 'Col',
    expirationDays: null,
  },
  'coliflor': {
    icon: require('./../../icons/Vegetales/coliflor_icon.png'),
    name: 'Coliflor',
    expirationDays: null,
  },
  'colrizada': {
    icon: require('./../../icons/Vegetales/col_rizada_icon.png'),
    name: 'Col Rizada',
    expirationDays: null,
  },
  'comida': {
    icon: require('./../../icons/Comidas/comida_icon.png'),
    name: 'Comida',
    expirationDays: null,
  },
  'comidaindia': {
    icon: require('./../../icons/Comidas/comida_india_icon.png'),
    name: 'Comida India',
    expirationDays: null,
  },
  'comidajaponesa': {
    icon: require('./../../icons/Comidas/comida_japonesa_icon.png'),
    name: 'Comida Japonesa',
    expirationDays: null,
  },
  'concha': {
    icon: require('./../../icons/Peces/concha_icon.png'),
    name: 'Concha',
    expirationDays: null,
  },
  'cono': {
    icon: require('./../../icons/Comidas/cono_icon.png'),
    name: 'Cono',
    expirationDays: null,
  },
  'conodepino': {
    icon: require('./../../icons/Frutas Secas/cono_de_pino_icon.png'),
    name: 'Cono De Pino',
    expirationDays: null,
  },
  'coral': {
    icon: require('./../../icons/Peces/coral_icon.png'),
    name: 'Coral',
    expirationDays: null,
  },
  'cordero': {
    icon: require('./../../icons/Carnes/cordero_icon.png'),
    name: 'Cordero',
    expirationDays: null,
  },
  'cosecha': {
    icon: require('./../../icons/Comidas/Cosecha_icon.png'),
    name: 'Cosecha',
    expirationDays: null,
  },
  'cosmopolita': {
    icon: require('./../../icons/Bebidas/cosmopolita_icon.png'),
    name: 'Cosmopolita',
    expirationDays: null,
  },
  'costillas': {
    icon: require('./../../icons/Carnes/costillas_icon.png'),
    name: 'Costillas',
    expirationDays: null,
  },
  'cremabatida': {
    icon: require('./../../icons/Lácteos/crema_batida_icon.png'),
    name: 'Crema Batida',
    expirationDays: null,
  },
  'cremafresca': {
    icon: require('./../../icons/Lácteos/crema_fresca_icon.png'),
    name: 'Crema Fresca',
    expirationDays: null,
  },
  'crepe': {
    icon: require('./../../icons/Comidas/crepe_icon.png'),
    name: 'Crepe',
    expirationDays: null,
  },
  'croissant': {
    icon: require('./../../icons/Dulces/Croissant_icon.png'),
    name: 'Croissant',
    expirationDays: null,
  },
  'cuajada': {
    icon: require('./../../icons/Lácteos/cuajada_icon.png'),
    name: 'Cuajada',
    expirationDays: null,
  },
  'cuarc': {
    icon: require('./../../icons/Lácteos/cuarc_icon.png'),
    name: 'Cuarc',
    expirationDays: null,
  },
  'cuerno': {
    icon: require('./../../icons/Comidas/cuerno_icon.png'),
    name: 'Cuerno',
    expirationDays: null,
  },
  'cupcake': {
    icon: require('./../../icons/Dulces/Cup_cake_icon.png'),
    name: 'Cup Cake',
    expirationDays: null,
  },
  'dadia': {
    icon: require('./../../icons/Lácteos/dadia_icon.png'),
    name: 'Dadia',
    expirationDays: null,
  },
  'dalgona': {
    icon: require('./../../icons/Bebidas/dalgona_icon.png'),
    name: 'Dalgona',
    expirationDays: null,
  },
  'dangke': {
    icon: require('./../../icons/Lácteos/dangke_icon.png'),
    name: 'Dangke',
    expirationDays: null,
  },
  'delfin': {
    icon: require('./../../icons/Peces/delfín_icon.png'),
    name: 'Delfín',
    expirationDays: null,
  },
  'descanso': {
    icon: require('./../../icons/Panes/descanso_icon.png'),
    name: 'Descanso',
    expirationDays: null,
  },
  'donas': {
    icon: require('./../../icons/Dulces/Donas_icon.png'),
    name: 'Donas',
    expirationDays: null,
  },
  'dosa': {
    icon: require('./../../icons/Comidas/dosa_icon.png'),
    name: 'Dosa',
    expirationDays: null,
  },
  'dragondefruta': {
    icon: require('./../../icons/Frutas/dragon_de_fruta_icon.png'),
    name: 'Dragon De Fruta',
    expirationDays: null,
  },
  'dulce': {
    icon: require('./../../icons/Comidas/dulce_icon.png'),
    name: 'Dulce',
    expirationDays: null,
  },
  'dulcedeleche': {
    icon: require('./../../icons/Lácteos/dulce_de_leche_icon.png'),
    name: 'Dulce De Leche',
    expirationDays: null,
  },
  'dulceria': {
    icon: require('./../../icons/Dulces/Dulcería_icon.png'),
    name: 'Dulcería',
    expirationDays: null,
  },
  'dulces': {
    icon: require('./../../icons/Dulces/dulces_icon.png'),
    name: 'Dulces',
    expirationDays: null,
  },
  'durian': {
    icon: require('./../../icons/Vegetales/durian_icon.png'),
    name: 'Durian',
    expirationDays: null,
  },
  'eclair': {
    icon: require('./../../icons/Dulces/eclair_icon.png'),
    name: 'Eclair',
    expirationDays: null,
  },
  'edamame': {
    icon: require('./../../icons/Legumbres/edamame_icon.png'),
    name: 'Edamame',
    expirationDays: null,
  },
  'embutido': {
    icon: require('./../../icons/Carnes/embutido_icon.png'),
    name: 'Embutido',
    expirationDays: null,
  },
  'empanadillas': {
    icon: require('./../../icons/Comidas/empanadillas_icon.png'),
    name: 'Empanadillas',
    expirationDays: null,
  },
  'emparedado': {
    icon: require('./../../icons/Comidas/emparedado_icon.png'),
    name: 'Emparedado',
    expirationDays: null,
  },
  'eneldo': {
    icon: require('./../../icons/Condimentos/eneldo_icon.png'),
    name: 'Eneldo',
    expirationDays: null,
  },
  'enescabeche': {
    icon: require('./../../icons/Condimentos/en_escabeche_icon.png'),
    name: 'En Escabeche',
    expirationDays: null,
  },
  'ensalada': {
    icon: require('./../../icons/Comidas/Ensalada_icon_2.png'),
    name: 'Ensalada',
    expirationDays: null,
  },
  'equilibrar': {
    icon: require('./../../icons/Dulces/equilibrar_icon.png'),
    name: 'Equilibrar',
    expirationDays: null,
  },
  'erizodemar': {
    icon: require('./../../icons/Peces/erizo_de_mar_icon.png'),
    name: 'Erizo De Mar',
    expirationDays: null,
  },
  'espaguetis': {
    icon: require('./../../icons/Comidas/Espaguetis_icon_1.png'),
    name: 'Espaguetis',
    expirationDays: null,
  },
  'esparrago': {
    icon: require('./../../icons/Comidas/Espárrago_icon.png'),
    name: 'Espárrago',
    expirationDays: null,
  },
  'esparragos': {
    icon: require('./../../icons/Condimentos/espárragos_icon.png'),
    name: 'Espárragos',
    expirationDays: null,
  },
  'espina': {
    icon: require('./../../icons/Peces/espina_icon.png'),
    name: 'Espina',
    expirationDays: null,
  },
  'espinacas': {
    icon: require('./../../icons/Vegetales/espinacas_icon.png'),
    name: 'Espinacas',
    expirationDays: null,
  },
  'estofado': {
    icon: require('./../../icons/Comidas/estofado_icon.png'),
    name: 'Estofado',
    expirationDays: null,
  },
  'estrellademar': {
    icon: require('./../../icons/Peces/estrella_de_mar_icon.png'),
    name: 'Estrella De Mar',
    expirationDays: null,
  },
  'filete': {
    icon: require('./../../icons/Carnes/filete_icon_1.png'),
    name: 'Filete',
    expirationDays: null,
  },
  'foca': {
    icon: require('./../../icons/Peces/foca_icon.png'),
    name: 'Foca',
    expirationDays: null,
  },
  'fondue': {
    icon: require('./../../icons/Dulces/fondue_icon.png'),
    name: 'Fondue',
    expirationDays: null,
  },
  'frambuesa': {
    icon: require('./../../icons/Frutas/frambuesa_icon.png'),
    name: 'Frambuesa',
    expirationDays: null,
  },
  'frape': {
    icon: require('./../../icons/Bebidas/frapé_icon.png'),
    name: 'Frapé',
    expirationDays: null,
  },
  'fresa': {
    icon: require('./../../icons/Dulces/Fresa_icon.png'),
    name: 'Fresa',
    expirationDays: null,
  },
  'frijoles': {
    icon: require('./../../icons/Legumbres/frijoles_icon.png'),
    name: 'Frijoles',
    expirationDays: null,
  },
  'frijolesrojos': {
    icon: require('./../../icons/Legumbres/frijoles_rojos_icon.png'),
    name: 'Frijoles Rojos',
    expirationDays: null,
  },
  'frijolitosconfitados': {
    icon: require('./../../icons/Dulces/frijolitos_confitados_icon.png'),
    name: 'Frijolitos Confitados',
    expirationDays: null,
  },
  'fruta': {
    icon: require('./../../icons/Comidas/fruta_icon.png'),
    name: 'Fruta',
    expirationDays: null,
  },
  'frutaestrella': {
    icon: require('./../../icons/Frutas/fruta_estrella_icon.png'),
    name: 'Fruta Estrella',
    expirationDays: null,
  },
  'frutas': {
    icon: require('./../../icons/Comidas/Frutas_icon.png'),
    name: 'Frutas',
    expirationDays: null,
  },
  'galleta': {
    icon: require('./../../icons/Dulces/galleta_icon.png'),
    name: 'Galleta',
    expirationDays: null,
  },
  'galletas': {
    icon: require('./../../icons/Comidas/galletas_icon.png'),
    name: 'Galletas',
    expirationDays: null,
  },
  'galletasalada': {
    icon: require('./../../icons/Comidas/galleta_salada_icon.png'),
    name: 'Galleta Salada',
    expirationDays: null,
  },
  'gamba': {
    icon: require('./../../icons/Comidas/gamba_icon.png'),
    name: 'Gamba',
    expirationDays: null,
  },
  'garbanzos': {
    icon: require('./../../icons/Legumbres/garbanzos_icon.png'),
    name: 'Garbanzos',
    expirationDays: null,
  },
  'gaviota': {
    icon: require('./../../icons/Peces/gaviota_icon.png'),
    name: 'Gaviota',
    expirationDays: null,
  },
  'gelatina': {
    icon: require('./../../icons/Comidas/gelatina_icon.png'),
    name: 'Gelatina',
    expirationDays: null,
  },
  'ghee': {
    icon: require('./../../icons/Lácteos/ghee_icon.png'),
    name: 'Ghee',
    expirationDays: null,
  },
  'glaciar': {
    icon: require('./../../icons/Dulces/glaciar_icon.png'),
    name: 'Glaciar',
    expirationDays: null,
  },
  'gofre': {
    icon: require('./../../icons/Comidas/gofre_icon.png'),
    name: 'Gofre',
    expirationDays: null,
  },
  'goji': {
    icon: require('./../../icons/Frutas/goji_icon.png'),
    name: 'Goji',
    expirationDays: null,
  },
  'gominola': {
    icon: require('./../../icons/Dulces/Gominola_icon.png'),
    name: 'Gominola',
    expirationDays: null,
  },
  'gragea': {
    icon: require('./../../icons/Dulces/Gragea_icon.png'),
    name: 'Gragea',
    expirationDays: null,
  },
  'granada': {
    icon: require('./../../icons/Frutas/granada_icon.png'),
    name: 'Granada',
    expirationDays: null,
  },
  'granos': {
    icon: require('./../../icons/Panes/granos_icon.png'),
    name: 'Granos',
    expirationDays: null,
  },
  'granosdecafe': {
    icon: require('./../../icons/Frutas Secas/granos_de_café_icon.png'),
    name: 'Granos De Café',
    expirationDays: null,
  },
  'guacamole': {
    icon: require('./../../icons/Comidas/Guacamole_icon_1.png'),
    name: 'Guacamole',
    expirationDays: null,
  },
  'guisantes': {
    icon: require('./../../icons/Legumbres/guisantes_icon.png'),
    name: 'Guisantes',
    expirationDays: null,
  },
  'habadesoja': {
    icon: require('./../../icons/Legumbres/haba_de_soja_icon.png'),
    name: 'Haba De Soja',
    expirationDays: null,
  },
  'hamburguesa': {
    icon: require('./../../icons/Carnes/hamburguesa_icon.png'),
    name: 'Hamburguesa',
    expirationDays: null,
  },
  'hamburguesaconqueso': {
    icon: require('./../../icons/Sandwich/hamburguesa_con_queso_icon.png'),
    name: 'Hamburguesa Con Queso',
    expirationDays: null,
  },
  'harina': {
    icon: require('./../../icons/Panes/harina_icon.png'),
    name: 'Harina',
    expirationDays: null,
  },
  'helado': {
    icon: require('./../../icons/Comidas/helado_icon.png'),
    name: 'Helado',
    expirationDays: null,
  },
  'heladoconfrutasynueces': {
    icon: require('./../../icons/Dulces/helado_con_frutas_y_nueces_icon.png'),
    name: 'Helado Con Frutas Y Nueces',
    expirationDays: null,
  },
  'hervido': {
    icon: require('./../../icons/Comidas/hervido_icon.png'),
    name: 'Hervido',
    expirationDays: null,
  },
  'hierba': {
    icon: require('./../../icons/Vegetales/hierba_icon.png'),
    name: 'Hierba',
    expirationDays: null,
  },
  'higado': {
    icon: require('./../../icons/Carnes/hígado_icon.png'),
    name: 'Hígado',
    expirationDays: null,
  },
  'higo': {
    icon: require('./../../icons/Frutas/higo_icon.png'),
    name: 'Higo',
    expirationDays: null,
  },
  'hinojo': {
    icon: require('./../../icons/Condimentos/hinojo_icon.png'),
    name: 'Hinojo',
    expirationDays: null,
  },
  'hoja': {
    icon: require('./../../icons/Variado/hoja_icon.png'),
    name: 'Hoja',
    expirationDays: null,
  },
  'hojadearce': {
    icon: require('./../../icons/Variado/hoja_de_arce_icon.png'),
    name: 'Hoja De Arce',
    expirationDays: null,
  },
  'hojaderoble': {
    icon: require('./../../icons/Variado/hoja_de_roble_icon.png'),
    name: 'Hoja De Roble',
    expirationDays: null,
  },
  'hojas': {
    icon: require('./../../icons/Condimentos/hojas_icon.png'),
    name: 'Hojas',
    expirationDays: null,
  },
  'hombredepandejengibre': {
    icon: require('./../../icons/Dulces/hombre_de_pan_de_jengibre_icon.png'),
    name: 'Hombre De Pan De Jengibre',
    expirationDays: null,
  },
  'hongos': {
    icon: require('./../../icons/Comidas/hongos_icon.png'),
    name: 'Hongos',
    expirationDays: null,
  },
  'horchata': {
    icon: require('./../../icons/Bebidas/horchata_icon.png'),
    name: 'Horchata',
    expirationDays: null,
  },
  'hornomicroondas': {
    icon: require('./../../icons/Panes/horno_microondas_icon.png'),
    name: 'Horno Microondas',
    expirationDays: null,
  },
  'hotdog': {
    icon: require('./../../icons/Comidas/hot_dog_icon.png'),
    name: 'Hot Dog',
    expirationDays: null,
  },
  'huevo': {
    icon: require('./../../icons/Comidas/huevo_icon.png'),
    name: 'Huevo',
    expirationDays: null,
  },
  'huevodechocolate': {
    icon: require('./../../icons/Dulces/huevo_de_chocolate_icon.png'),
    name: 'Huevo De Chocolate',
    expirationDays: null,
  },
  'huevos': {
    icon: require('./../../icons/Comidas/huevos_icon.png'),
    name: 'Huevos',
    expirationDays: null,
  },
  'huevosfritos': {
    icon: require('./../../icons/Comidas/huevos_fritos_icon.png'),
    name: 'Huevos Fritos',
    expirationDays: null,
  },
  'hummus': {
    icon: require('./../../icons/Comidas/Hummus_icon.png'),
    name: 'Hummus',
    expirationDays: null,
  },
  'idolomoro': {
    icon: require('./../../icons/Peces/Ídolo_moro_icon.png'),
    name: 'Ídolo Moro',
    expirationDays: null,
  },
  'indio': {
    icon: require('./../../icons/Comidas/indio_icon.png'),
    name: 'Indio',
    expirationDays: null,
  },
  'infusion': {
    icon: require('./../../icons/Bebidas/infusión_icon.png'),
    name: 'Infusión',
    expirationDays: null,
  },
  'jamon': {
    icon: require('./../../icons/Carnes/jamón_icon.png'),
    name: 'Jamón',
    expirationDays: null,
  },
  'jengibre': {
    icon: require('./../../icons/Condimentos/jengibre_icon.png'),
    name: 'Jengibre',
    expirationDays: null,
  },
  'judiasverdes': {
    icon: require('./../../icons/Legumbres/judías_verdes_icon.png'),
    name: 'Judías Verdes',
    expirationDays: null,
  },
  'jugo': {
    icon: require('./../../icons/Bebidas/jugo_icon.png'),
    name: 'Jugo',
    expirationDays: null,
  },
  'junquillo': {
    icon: require('./../../icons/Panes/junquillo_icon.png'),
    name: 'Junquillo',
    expirationDays: null,
  },
  'kefir': {
    icon: require('./../../icons/Lácteos/kéfir_icon.png'),
    name: 'Kéfir',
    expirationDays: null,
  },
  'kiwi': {
    icon: require('./../../icons/Frutas/kiwi_icon.png'),
    name: 'Kiwi',
    expirationDays: null,
  },
  'kofta': {
    icon: require('./../../icons/Comidas/kofta_icon.png'),
    name: 'Kofta',
    expirationDays: null,
  },
  'kombucha': {
    icon: require('./../../icons/Bebidas/kombucha_icon.png'),
    name: 'Kombucha',
    expirationDays: null,
  },
  'kulfi': {
    icon: require('./../../icons/Lácteos/kulfi_icon.png'),
    name: 'Kulfi',
    expirationDays: null,
  },
  'lactoso': {
    icon: require('./../../icons/Dulces/lactoso_icon.png'),
    name: 'Lactoso',
    expirationDays: null,
  },
  'laddu': {
    icon: require('./../../icons/Comidas/laddu_icon.png'),
    name: 'Laddu',
    expirationDays: null,
  },
  'lahierbadelimon': {
    icon: require('./../../icons/Condimentos/la_hierba_de_limón_icon.png'),
    name: 'La Hierba De Limón',
    expirationDays: null,
  },
  'langosta': {
    icon: require('./../../icons/Comidas/langosta_icon.png'),
    name: 'Langosta',
    expirationDays: null,
  },
  'lasmanzanas': {
    icon: require('./../../icons/Comidas/las_manzanas_icon.png'),
    name: 'Las Manzanas',
    expirationDays: null,
  },
  'lassi': {
    icon: require('./../../icons/Lácteos/lassi_icon.png'),
    name: 'Lassi',
    expirationDays: null,
  },
  'lata': {
    icon: require('./../../icons/Comidas/lata_icon.png'),
    name: 'Lata',
    expirationDays: null,
  },
  'lattemacchiato': {
    icon: require('./../../icons/Bebidas/latte_macchiato_icon.png'),
    name: 'Latte Macchiato',
    expirationDays: null,
  },
  'leche': {
    icon: require('./../../icons/Bebidas/leche_icon.png'),
    name: 'Leche',
    expirationDays: null,
  },
  'lecheconchocolate': {
    icon: require('./../../icons/Bebidas/leche_con_chocolate_icon.png'),
    name: 'Leche Con Chocolate',
    expirationDays: null,
  },
  'lechecondensada': {
    icon: require('./../../icons/Lácteos/leche_condensada_icon.png'),
    name: 'Leche Condensada',
    expirationDays: null,
  },
  'lechedealmendras': {
    icon: require('./../../icons/Comidas/Leche_de_almendras_icon.png'),
    name: 'Leche De Almendras',
    expirationDays: null,
  },
  'lechedecamello': {
    icon: require('./../../icons/Lácteos/leche_de_camello_icon.png'),
    name: 'Leche De Camello',
    expirationDays: null,
  },
  'lechedecoco': {
    icon: require('./../../icons/Condimentos/leche_de_coco_icon.png'),
    name: 'Leche De Coco',
    expirationDays: null,
  },
  'lechedefresa': {
    icon: require('./../../icons/Bebidas/leche_de_fresa_icon.png'),
    name: 'Leche De Fresa',
    expirationDays: null,
  },
  'lechedeoveja': {
    icon: require('./../../icons/Lácteos/leche_de_oveja_icon.png'),
    name: 'Leche De Oveja',
    expirationDays: null,
  },
  'lecheenpolvo': {
    icon: require('./../../icons/Lácteos/leche_en_polvo_icon.png'),
    name: 'Leche En Polvo',
    expirationDays: null,
  },
  'lechuga': {
    icon: require('./../../icons/Vegetales/lechuga_icon.png'),
    name: 'Lechuga',
    expirationDays: null,
  },
  'lentejas': {
    icon: require('./../../icons/Legumbres/lentejas_icon.png'),
    name: 'Lentejas',
    expirationDays: null,
  },
  'licordehierbas': {
    icon: require('./../../icons/Bebidas/licor_de_hierbas_icon.png'),
    name: 'Licor De Hierbas',
    expirationDays: null,
  },
  'licorera': {
    icon: require('./../../icons/Bebidas/licorera_icon.png'),
    name: 'Licorera',
    expirationDays: null,
  },
  'licuadora': {
    icon: require('./../../icons/Comidas/Licuadora_icon.png'),
    name: 'Licuadora',
    expirationDays: null,
  },
  'lima': {
    icon: require('./../../icons/Frutas/lima_icon.png'),
    name: 'Lima',
    expirationDays: null,
  },
  'limon': {
    icon: require('./../../icons/Comidas/limón_icon.png'),
    name: 'Limón',
    expirationDays: null,
  },
  'limonada': {
    icon: require('./../../icons/Bebidas/limonada_icon.png'),
    name: 'Limonada',
    expirationDays: null,
  },
  'linterna': {
    icon: require('./../../icons/Variado/linterna_icon.png'),
    name: 'Linterna',
    expirationDays: null,
  },
  'lostomates': {
    icon: require('./../../icons/Comidas/los_tomates_icon.png'),
    name: 'Los Tomates',
    expirationDays: null,
  },
  'lychee': {
    icon: require('./../../icons/Frutas/lychee_icon.png'),
    name: 'Lychee',
    expirationDays: null,
  },
  'macadamia': {
    icon: require('./../../icons/Frutas Secas/macadamia_icon.png'),
    name: 'Macadamia',
    expirationDays: null,
  },
  'macaron': {
    icon: require('./../../icons/Dulces/macaron_icon.png'),
    name: 'Macaron',
    expirationDays: null,
  },
  'macarones': {
    icon: require('./../../icons/Dulces/Macarones_icon.png'),
    name: 'Macarones',
    expirationDays: null,
  },
  'macarons': {
    icon: require('./../../icons/Dulces/macarons_icon.png'),
    name: 'Macarons',
    expirationDays: null,
  },
  'macarron': {
    icon: require('./../../icons/Comidas/macarrón_icon.png'),
    name: 'Macarrón',
    expirationDays: null,
  },
  'macedonia': {
    icon: require('./../../icons/Comidas/Macedonia_icon.png'),
    name: 'Macedonia',
    expirationDays: null,
  },
  'madera': {
    icon: require('./../../icons/Variado/madera_icon.png'),
    name: 'Madera',
    expirationDays: null,
  },
  'magdalena': {
    icon: require('./../../icons/Comidas/magdalena_icon.png'),
    name: 'Magdalena',
    expirationDays: null,
  },
  'maiz': {
    icon: require('./../../icons/Legumbres/maíz_icon.png'),
    name: 'Maíz',
    expirationDays: null,
  },
  'malteada': {
    icon: require('./../../icons/Bebidas/malteada_icon.png'),
    name: 'Malteada',
    expirationDays: null,
  },
  'malvavisco': {
    icon: require('./../../icons/Dulces/Malvavisco_icon.png'),
    name: 'Malvavisco',
    expirationDays: null,
  },
  'malvaviscos': {
    icon: require('./../../icons/Dulces/malvaviscos_icon.png'),
    name: 'Malvaviscos',
    expirationDays: null,
  },
  'mango': {
    icon: require('./../../icons/Frutas/mango_icon.png'),
    name: 'Mango',
    expirationDays: null,
  },
  'mangostan': {
    icon: require('./../../icons/Vegetales/mangostán_icon.png'),
    name: 'Mangostán',
    expirationDays: null,
  },
  'mani': {
    icon: require('./../../icons/Frutas Secas/maní_icon.png'),
    name: 'Maní',
    expirationDays: null,
  },
  'manteca': {
    icon: require('./../../icons/Condimentos/manteca_icon.png'),
    name: 'Manteca',
    expirationDays: null,
  },
  'mantecadecacahuete': {
    icon: require('./../../icons/Dulces/Manteca_de_cacahuete_icon.png'),
    name: 'Manteca De Cacahuete',
    expirationDays: null,
  },
  'manzana': {
    icon: require('./../../icons/Frutas/manzana_icon.png'),
    name: 'Manzana',
    expirationDays: 30,
  },
  'manzanacaramelizada': {
    icon: require('./../../icons/Dulces/manzana_caramelizada_icon.png'),
    name: 'Manzana Caramelizada',
    expirationDays: null,
  },
  'manzanarosa': {
    icon: require('./../../icons/Frutas/manzana_rosa_icon.png'),
    name: 'Manzana Rosa',
    expirationDays: null,
  },
  'maquinadedulces': {
    icon: require('./../../icons/Dulces/maquina_de_dulces_icon.png'),
    name: 'Maquina De Dulces',
    expirationDays: null,
  },
  'maracuya': {
    icon: require('./../../icons/Frutas/maracuyá_icon.png'),
    name: 'Maracuyá',
    expirationDays: null,
  },
  'margarita': {
    icon: require('./../../icons/Bebidas/margarita_icon.png'),
    name: 'Margarita',
    expirationDays: null,
  },
  'martini': {
    icon: require('./../../icons/Bebidas/martini_icon.png'),
    name: 'Martini',
    expirationDays: null,
  },
  'masa': {
    icon: require('./../../icons/Panes/masa_icon.png'),
    name: 'Masa',
    expirationDays: null,
  },
  'masalapapad': {
    icon: require('./../../icons/Comidas/masala_papad_icon.png'),
    name: 'Masala Papad',
    expirationDays: null,
  },
  'matcha': {
    icon: require('./../../icons/Bebidas/matcha_icon.png'),
    name: 'Matcha',
    expirationDays: null,
  },
  'mayonesa': {
    icon: require('./../../icons/Comidas/mayonesa_icon.png'),
    name: 'Mayonesa',
    expirationDays: null,
  },
  'mazorca': {
    icon: require('./../../icons/Comidas/mazorca_icon.png'),
    name: 'Mazorca',
    expirationDays: null,
  },
  'medusa': {
    icon: require('./../../icons/Peces/medusa_icon.png'),
    name: 'Medusa',
    expirationDays: null,
  },
  'mejillon': {
    icon: require('./../../icons/Peces/mejillón_icon.png'),
    name: 'Mejillón',
    expirationDays: null,
  },
  'melocoton': {
    icon: require('./../../icons/Frutas/melocotón_icon.png'),
    name: 'Melocotón',
    expirationDays: null,
  },
  'melon': {
    icon: require('./../../icons/Frutas/melón_icon.png'),
    name: 'Melón',
    expirationDays: null,
  },
  'membrillo': {
    icon: require('./../../icons/Frutas/membrillo_icon.png'),
    name: 'Membrillo',
    expirationDays: null,
  },
  'menta': {
    icon: require('./../../icons/Condimentos/menta_icon.png'),
    name: 'Menta',
    expirationDays: null,
  },
  'mermelada': {
    icon: require('./../../icons/Dulces/Mermelada_icon.png'),
    name: 'Mermelada',
    expirationDays: null,
  },
  'mermeladadefresa': {
    icon: require('./../../icons/Condimentos/mermelada_de_fresa_icon.png'),
    name: 'Mermelada De Fresa',
    expirationDays: null,
  },
  'miel': {
    icon: require('./../../icons/Condimentos/miel_icon.png'),
    name: 'Miel',
    expirationDays: null,
  },
  'mieldemaple': {
    icon: require('./../../icons/Condimentos/miel_de_maple_icon.png'),
    name: 'Miel De Maple',
    expirationDays: null,
  },
  'mimosa': {
    icon: require('./../../icons/Bebidas/mimosa_icon.png'),
    name: 'Mimosa',
    expirationDays: null,
  },
  'mochaccino': {
    icon: require('./../../icons/Bebidas/mochaccino_icon.png'),
    name: 'Mochaccino',
    expirationDays: null,
  },
  'mojito': {
    icon: require('./../../icons/Bebidas/mojito_icon.png'),
    name: 'Mojito',
    expirationDays: null,
  },
  'mollete': {
    icon: require('./../../icons/Comidas/mollete_icon.png'),
    name: 'Mollete',
    expirationDays: null,
  },
  'mostaza': {
    icon: require('./../../icons/Condimentos/mostaza_icon.png'),
    name: 'Mostaza',
    expirationDays: null,
  },
  'motivo': {
    icon: require('./../../icons/Bebidas/motivo_icon.png'),
    name: 'Motivo',
    expirationDays: null,
  },
  'nabo': {
    icon: require('./../../icons/Vegetales/nabo_icon.png'),
    name: 'Nabo',
    expirationDays: null,
  },
  'nachos': {
    icon: require('./../../icons/Comidas/nachos_icon.png'),
    name: 'Nachos',
    expirationDays: null,
  },
  'naranja': {
    icon: require('./../../icons/Dulces/naranja_icon.png'),
    name: 'Naranja',
    expirationDays: null,
  },
  'naranjas': {
    icon: require('./../../icons/Comidas/naranjas_icon.png'),
    name: 'Naranjas',
    expirationDays: null,
  },
  'nata': {
    icon: require('./../../icons/Lácteos/nata_icon.png'),
    name: 'Nata',
    expirationDays: null,
  },
  'natillasappel': {
    icon: require('./../../icons/Vegetales/natillas_appel_icon.png'),
    name: 'Natillas Appel',
    expirationDays: null,
  },
  'nueces': {
    icon: require('./../../icons/Comidas/nueces_icon.png'),
    name: 'Nueces',
    expirationDays: null,
  },
  'nuecesdebrasil': {
    icon: require('./../../icons/Frutas Secas/nueces_de_brasil_icon.png'),
    name: 'Nueces De Brasil',
    expirationDays: null,
  },
  'nuez': {
    icon: require('./../../icons/Frutas Secas/nuez_icon.png'),
    name: 'Nuez',
    expirationDays: null,
  },
  'nuezmoscada': {
    icon: require('./../../icons/Condimentos/nuez_moscada_icon.png'),
    name: 'Nuez Moscada',
    expirationDays: null,
  },
  'oblea': {
    icon: require('./../../icons/Dulces/oblea_icon.png'),
    name: 'Oblea',
    expirationDays: null,
  },
  'onigiri': {
    icon: require('./../../icons/Comidas/onigiri_icon.png'),
    name: 'Onigiri',
    expirationDays: null,
  },
  'orca': {
    icon: require('./../../icons/Peces/orca_icon.png'),
    name: 'Orca',
    expirationDays: null,
  },
  'ositodegoma': {
    icon: require('./../../icons/Dulces/osito_de_goma_icon.png'),
    name: 'Osito De Goma',
    expirationDays: null,
  },
  'oso': {
    icon: require('./../../icons/Variado/oso_icon.png'),
    name: 'Oso',
    expirationDays: null,
  },
  'osodegominola': {
    icon: require('./../../icons/Dulces/Oso_de_gominola_icon.png'),
    name: 'Oso De Gominola',
    expirationDays: null,
  },
  'ostra': {
    icon: require('./../../icons/Comidas/ostra_icon.png'),
    name: 'Ostra',
    expirationDays: null,
  },
  'pacana': {
    icon: require('./../../icons/Frutas Secas/pacana_icon.png'),
    name: 'Pacana',
    expirationDays: null,
  },
  'pajaro': {
    icon: require('./../../icons/Variado/pájaro_icon.png'),
    name: 'Pájaro',
    expirationDays: null,
  },
  'paletadehielo': {
    icon: require('./../../icons/Dulces/paleta_de_hielo_icon.png'),
    name: 'Paleta De Hielo',
    expirationDays: null,
  },
  'palitodepaleta': {
    icon: require('./../../icons/Dulces/palito_de_paleta_icon.png'),
    name: 'Palito De Paleta',
    expirationDays: null,
  },
  'palmeradatilera': {
    icon: require('./../../icons/Vegetales/palmera_datilera_icon.png'),
    name: 'Palmera Datilera',
    expirationDays: null,
  },
  'palodedulce': {
    icon: require('./../../icons/Dulces/palo_de_dulce_icon.png'),
    name: 'Palo De Dulce',
    expirationDays: null,
  },
  'palodehelado': {
    icon: require('./../../icons/Dulces/Palo_de_helado_icon.png'),
    name: 'Palo De Helado',
    expirationDays: null,
  },
  'palomitasdemaiz': {
    icon: require('./../../icons/Comidas/palomitas_de_maiz_icon.png'),
    name: 'Palomitas De Maiz',
    expirationDays: null,
  },
  'pan': {
    icon: require('./../../icons/Comidas/Pan_icon.png'),
    name: 'Pan',
    expirationDays: null,
  },
  'panal': {
    icon: require('./../../icons/Dulces/panal_icon.png'),
    name: 'Panal',
    expirationDays: null,
  },
  'pancho': {
    icon: require('./../../icons/Comidas/pancho_icon.png'),
    name: 'Pancho',
    expirationDays: null,
  },
  'pandemolde': {
    icon: require('./../../icons/Comidas/pan_de_molde_icon.png'),
    name: 'Pan De Molde',
    expirationDays: null,
  },
  'panintegral': {
    icon: require('./../../icons/Panes/pan_integral_icon.png'),
    name: 'Pan Integral',
    expirationDays: null,
  },
  'pannacotta': {
    icon: require('./../../icons/Dulces/panna_cotta_icon.png'),
    name: 'Panna Cotta',
    expirationDays: null,
  },
  'panqueques': {
    icon: require('./../../icons/Comidas/panqueques_icon.png'),
    name: 'Panqueques',
    expirationDays: null,
  },
  'papa': {
    icon: require('./../../icons/Condimentos/papa_icon.png'),
    name: 'Papa',
    expirationDays: null,
  },
  'papasfritas': {
    icon: require('./../../icons/Comidas/papas_fritas_icon.png'),
    name: 'Papas Fritas',
    expirationDays: null,
  },
  'papaya': {
    icon: require('./../../icons/Comidas/papaya_icon.png'),
    name: 'Papaya',
    expirationDays: null,
  },
  'parilla': {
    icon: require('./../../icons/Comidas/parilla_icon.png'),
    name: 'Parilla',
    expirationDays: null,
  },
  'pasta': {
    icon: require('./../../icons/Comidas/pasta_icon.png'),
    name: 'Pasta',
    expirationDays: null,
  },
  'pastel': {
    icon: require('./../../icons/Comidas/pastel_icon.png'),
    name: 'Pastel',
    expirationDays: null,
  },
  'pasteldecumpleanos': {
    icon: require('./../../icons/Dulces/pastel_de_cumpleaños_icon.png'),
    name: 'Pastel De Cumpleaños',
    expirationDays: null,
  },
  'pasteldefresa': {
    icon: require('./../../icons/Dulces/pastel_de_fresa_icon.png'),
    name: 'Pastel De Fresa',
    expirationDays: null,
  },
  'pastelderollo': {
    icon: require('./../../icons/Dulces/pastel_de_rollo_icon.png'),
    name: 'Pastel De Rollo',
    expirationDays: null,
  },
  'pasteldezanahoria': {
    icon: require('./../../icons/Dulces/pastel_de_zanahoria_icon.png'),
    name: 'Pastel De Zanahoria',
    expirationDays: null,
  },
  'pasteleria': {
    icon: require('./../../icons/Comidas/pastelería_icon.png'),
    name: 'Pastelería',
    expirationDays: null,
  },
  'patatas': {
    icon: require('./../../icons/Comidas/Patatas_icon.png'),
    name: 'Patatas',
    expirationDays: null,
  },
  'patatasfritas': {
    icon: require('./../../icons/Dulces/patatas_fritas_icon.png'),
    name: 'Patatas Fritas',
    expirationDays: null,
  },
  'pechugadepollo': {
    icon: require('./../../icons/Carnes/pechuga_De_pollo_icon_3.png'),
    name: 'Pechuga De Pollo',
    expirationDays: null,
  },
  'pegar': {
    icon: require('./../../icons/Carnes/pegar_icon.png'),
    name: 'Pegar',
    expirationDays: null,
  },
  'pepino': {
    icon: require('./../../icons/Vegetales/pepino_icon.png'),
    name: 'Pepino',
    expirationDays: null,
  },
  'pepperoni': {
    icon: require('./../../icons/Comidas/pepperoni_icon.png'),
    name: 'Pepperoni',
    expirationDays: null,
  },
  'pera': {
    icon: require('./../../icons/Frutas/pera_icon.png'),
    name: 'Pera',
    expirationDays: null,
  },
  'peras': {
    icon: require('./../../icons/Comidas/Peras_icon.png'),
    name: 'Peras',
    expirationDays: null,
  },
  'pescado': {
    icon: require('./../../icons/Comidas/pescado_icon.png'),
    name: 'Pescado',
    expirationDays: null,
  },
  'pez': {
    icon: require('./../../icons/Comidas/pez_icon.png'),
    name: 'Pez',
    expirationDays: null,
  },
  'pezcirujano': {
    icon: require('./../../icons/Peces/pez_cirujano_icon.png'),
    name: 'Pez Cirujano',
    expirationDays: null,
  },
  'pezespada': {
    icon: require('./../../icons/Peces/pez_espada_icon.png'),
    name: 'Pez Espada',
    expirationDays: null,
  },
  'pezglobo': {
    icon: require('./../../icons/Peces/pez_globo_icon.png'),
    name: 'Pez Globo',
    expirationDays: null,
  },
  'pezluna': {
    icon: require('./../../icons/Peces/pez_luna_icon.png'),
    name: 'Pez Luna',
    expirationDays: null,
  },
  'pezmartillo': {
    icon: require('./../../icons/Peces/pez_martillo_icon.png'),
    name: 'Pez Martillo',
    expirationDays: null,
  },
  'pezpayaso': {
    icon: require('./../../icons/Peces/pez_payaso_icon.png'),
    name: 'Pez Payaso',
    expirationDays: null,
  },
  'pezvolador': {
    icon: require('./../../icons/Peces/pez_volador_icon.png'),
    name: 'Pez Volador',
    expirationDays: null,
  },
  'physalis': {
    icon: require('./../../icons/Vegetales/physalis_icon.png'),
    name: 'Physalis',
    expirationDays: null,
  },
  'piedemanzana': {
    icon: require('./../../icons/Dulces/pie_de_manzana_icon.png'),
    name: 'Pie De Manzana',
    expirationDays: null,
  },
  'piernadejamon': {
    icon: require('./../../icons/Comidas/pierna_de_jamón_icon.png'),
    name: 'Pierna De Jamón',
    expirationDays: null,
  },
  'piernadepollo': {
    icon: require('./../../icons/Carnes/pierna_de_pollo_icon.png'),
    name: 'Pierna De Pollo',
    expirationDays: null,
  },
  'piernasdepollo': {
    icon: require('./../../icons/Carnes/piernas_de_pollo_icon_1.png'),
    name: 'Piernas De Pollo',
    expirationDays: null,
  },
  'pimienta': {
    icon: require('./../../icons/Comidas/Pimienta_icon.png'),
    name: 'Pimienta',
    expirationDays: null,
  },
  'pimientomorron': {
    icon: require('./../../icons/Condimentos/pimiento_morrón_icon.png'),
    name: 'Pimiento Morrón',
    expirationDays: null,
  },
  'pimientopicante': {
    icon: require('./../../icons/Condimentos/pimiento_picante_icon.png'),
    name: 'Pimiento Picante',
    expirationDays: null,
  },
  'pina': {
    icon: require('./../../icons/Comidas/piña_icon.png'),
    name: 'Piña',
    expirationDays: null,
  },
  'pinacolada': {
    icon: require('./../../icons/Bebidas/piña_colada_icon.png'),
    name: 'Piña Colada',
    expirationDays: null,
  },
  'pinguino': {
    icon: require('./../../icons/Peces/pingüino_icon.png'),
    name: 'Pingüino',
    expirationDays: null,
  },
  'piruleta': {
    icon: require('./../../icons/Dulces/Piruleta_icon.png'),
    name: 'Piruleta',
    expirationDays: null,
  },
  'piruli': {
    icon: require('./../../icons/Dulces/pirulí_icon.png'),
    name: 'Pirulí',
    expirationDays: null,
  },
  'pistacho': {
    icon: require('./../../icons/Frutas Secas/pistacho_icon.png'),
    name: 'Pistacho',
    expirationDays: null,
  },
  'pizza': {
    icon: require('./../../icons/Comidas/Pizza_icon_3.png'),
    name: 'Pizza',
    expirationDays: null,
  },
  'platano': {
    icon: require('./../../icons/Frutas/plátano_icon.png'),
    name: 'Plátano',
    expirationDays: null,
  },
  'poder': {
    icon: require('./../../icons/Comidas/poder_icon.png'),
    name: 'Poder',
    expirationDays: null,
  },
  'pollo': {
    icon: require('./../../icons/Carnes/pollo_icon.png'),
    name: 'Pollo',
    expirationDays: null,
  },
  'polloasado': {
    icon: require('./../../icons/Comidas/pollo_asado_icon.png'),
    name: 'Pollo Asado',
    expirationDays: null,
  },
  'polloentero': {
    icon: require('./../../icons/Carnes/pollo_entero_icon.png'),
    name: 'Pollo Entero',
    expirationDays: null,
  },
  'pomelo': {
    icon: require('./../../icons/Comidas/Pomelo_icon.png'),
    name: 'Pomelo',
    expirationDays: null,
  },
  'pudin': {
    icon: require('./../../icons/Comidas/Pudín_icon.png'),
    name: 'Pudín',
    expirationDays: null,
  },
  'puercoespin': {
    icon: require('./../../icons/Variado/puerco_espín_icon.png'),
    name: 'Puerco Espín',
    expirationDays: null,
  },
  'puerro': {
    icon: require('./../../icons/Vegetales/puerro_icon.png'),
    name: 'Puerro',
    expirationDays: null,
  },
  'pulpo': {
    icon: require('./../../icons/Peces/pulpo_icon.png'),
    name: 'Pulpo',
    expirationDays: null,
  },
  'punetazo': {
    icon: require('./../../icons/Bebidas/puñetazo_icon.png'),
    name: 'Puñetazo',
    expirationDays: null,
  },
  'puredepatatas': {
    icon: require('./../../icons/Comidas/Puré_de_patatas_icon.png'),
    name: 'Puré De Patatas',
    expirationDays: null,
  },
  'queso': {
    icon: require('./../../icons/Comidas/queso_icon.png'),
    name: 'Queso',
    expirationDays: null,
  },
  'quesocheddar': {
    icon: require('./../../icons/Comidas/queso_cheddar_icon.png'),
    name: 'Queso Cheddar',
    expirationDays: null,
  },
  'quesoedam': {
    icon: require('./../../icons/Lácteos/queso_edam_icon.png'),
    name: 'Queso Edam',
    expirationDays: null,
  },
  'quesomozzarella': {
    icon: require('./../../icons/Lácteos/queso_mozzarella_icon.png'),
    name: 'Queso Mozzarella',
    expirationDays: null,
  },
  'quesosuizo': {
    icon: require('./../../icons/Lácteos/queso_suizo_icon.png'),
    name: 'Queso Suizo',
    expirationDays: null,
  },
  'rabano': {
    icon: require('./../../icons/Vegetales/rábano_icon.png'),
    name: 'Rábano',
    expirationDays: null,
  },
  'rama': {
    icon: require('./../../icons/Variado/rama_icon.png'),
    name: 'Rama',
    expirationDays: null,
  },
  'ramen': {
    icon: require('./../../icons/Comidas/Ramen_icon.png'),
    name: 'Ramen',
    expirationDays: null,
  },
  'ramune': {
    icon: require('./../../icons/Bebidas/ramune_icon.png'),
    name: 'Ramune',
    expirationDays: null,
  },
  'rape': {
    icon: require('./../../icons/Peces/rape_icon.png'),
    name: 'Rape',
    expirationDays: null,
  },
  'rayo': {
    icon: require('./../../icons/Peces/rayo_icon.png'),
    name: 'Rayo',
    expirationDays: null,
  },
  'reajustesalarial': {
    icon: require('./../../icons/Bebidas/reajuste_salarial_icon.png'),
    name: 'Reajuste Salarial',
    expirationDays: null,
  },
  'rebanadadepizza': {
    icon: require('./../../icons/Comidas/Rebanada_de_pizza_icon.png'),
    name: 'Rebanada De Pizza',
    expirationDays: null,
  },
  'rebanadoradepan': {
    icon: require('./../../icons/Panes/rebanadora_de_pan_icon.png'),
    name: 'Rebanadora De Pan',
    expirationDays: null,
  },
  'refresco': {
    icon: require('./../../icons/Bebidas/refresco_icon.png'),
    name: 'Refresco',
    expirationDays: null,
  },
  'regaliz': {
    icon: require('./../../icons/Dulces/regaliz_icon.png'),
    name: 'Regaliz',
    expirationDays: null,
  },
  'remolacha': {
    icon: require('./../../icons/Vegetales/remolacha_icon.png'),
    name: 'Remolacha',
    expirationDays: null,
  },
  'repollo': {
    icon: require('./../../icons/Vegetales/repollo_icon.png'),
    name: 'Repollo',
    expirationDays: null,
  },
  'repollorojo': {
    icon: require('./../../icons/Vegetales/repollo_rojo_icon.png'),
    name: 'Repollo Rojo',
    expirationDays: null,
  },
  'requeson': {
    icon: require('./../../icons/Lácteos/requesón_icon.png'),
    name: 'Requesón',
    expirationDays: null,
  },
  'res': {
    icon: require('./../../icons/Carnes/res_icon_3.png'),
    name: 'Res',
    expirationDays: null,
  },
  'ricotta': {
    icon: require('./../../icons/Lácteos/ricotta_icon.png'),
    name: 'Ricotta',
    expirationDays: null,
  },
  'rinon': {
    icon: require('./../../icons/Carnes/riñón_icon.png'),
    name: 'Riñón',
    expirationDays: null,
  },
  'rodillo': {
    icon: require('./../../icons/Dulces/rodillo_icon.png'),
    name: 'Rodillo',
    expirationDays: null,
  },
  'rollodecanela': {
    icon: require('./../../icons/Dulces/rollo_de_canela_icon.png'),
    name: 'Rollo De Canela',
    expirationDays: null,
  },
  'rollodesushi': {
    icon: require('./../../icons/Comidas/rollo_de_sushi_icon.png'),
    name: 'Rollo De Sushi',
    expirationDays: null,
  },
  'romero': {
    icon: require('./../../icons/Condimentos/romero_icon.png'),
    name: 'Romero',
    expirationDays: null,
  },
  'ron': {
    icon: require('./../../icons/Bebidas/ron_icon.png'),
    name: 'Ron',
    expirationDays: null,
  },
  'rosquilla': {
    icon: require('./../../icons/Comidas/rosquilla_icon.png'),
    name: 'Rosquilla',
    expirationDays: null,
  },
  'rucula': {
    icon: require('./../../icons/Condimentos/rúcula_icon.png'),
    name: 'Rúcula',
    expirationDays: null,
  },
  'sal': {
    icon: require('./../../icons/Condimentos/sal_icon.png'),
    name: 'Sal',
    expirationDays: null,
  },
  'salami': {
    icon: require('./../../icons/Carnes/salami_icon.png'),
    name: 'Salami',
    expirationDays: null,
  },
  'salchicha': {
    icon: require('./../../icons/Carnes/salchicha_icon.png'),
    name: 'Salchicha',
    expirationDays: null,
  },
  'salchichas': {
    icon: require('./../../icons/Carnes/salchichas_icon.png'),
    name: 'Salchichas',
    expirationDays: null,
  },
  'salmon': {
    icon: require('./../../icons/Comidas/salmón_icon.png'),
    name: 'Salmón',
    expirationDays: null,
  },
  'salsa': {
    icon: require('./../../icons/Condimentos/salsa_icon.png'),
    name: 'Salsa',
    expirationDays: null,
  },
  'salsadechile': {
    icon: require('./../../icons/Condimentos/salsa_de_chile_icon.png'),
    name: 'Salsa De Chile',
    expirationDays: null,
  },
  'salsadetomate': {
    icon: require('./../../icons/Comidas/salsa_de_tomate_icon.png'),
    name: 'Salsa De Tomate',
    expirationDays: null,
  },
  'salvia': {
    icon: require('./../../icons/Condimentos/salvia_icon.png'),
    name: 'Salvia',
    expirationDays: null,
  },
  'samosa': {
    icon: require('./../../icons/Comidas/samosa_icon.png'),
    name: 'Samosa',
    expirationDays: null,
  },
  'sandia': {
    icon: require('./../../icons/Comidas/sandía_icon.png'),
    name: 'Sandía',
    expirationDays: null,
  },
  'sandwich': {
    icon: require('./../../icons/Sandwich/Sandwich_icon_17.png'),
    name: 'Sandwich',
    expirationDays: null,
  },
  'sandwichdehamburguesa': {
    icon: require('./../../icons/Sandwich/sandwich_de_hamburguesa_icon.png'),
    name: 'Sandwich De Hamburguesa',
    expirationDays: null,
  },
  'sandwichdehelado': {
    icon: require('./../../icons/Dulces/sándwich_de_helado_icon.png'),
    name: 'Sándwich De Helado',
    expirationDays: null,
  },
  'sandwichdehotdog': {
    icon: require('./../../icons/Sandwich/sandwich_de_hot_dog_icon.png'),
    name: 'Sandwich De Hot Dog',
    expirationDays: null,
  },
  'sangria': {
    icon: require('./../../icons/Bebidas/sangría_icon.png'),
    name: 'Sangría',
    expirationDays: null,
  },
  'sardina': {
    icon: require('./../../icons/Peces/sardina_icon.png'),
    name: 'Sardina',
    expirationDays: null,
  },
  'semilladecalabaza': {
    icon: require('./../../icons/Frutas Secas/semilla_de_calabaza_icon.png'),
    name: 'Semilla De Calabaza',
    expirationDays: null,
  },
  'semilladegirasol': {
    icon: require('./../../icons/Frutas Secas/semilla_de_girasol_icon.png'),
    name: 'Semilla De Girasol',
    expirationDays: null,
  },
  'semilladelino': {
    icon: require('./../../icons/Frutas Secas/semilla_de_lino_icon.png'),
    name: 'Semilla De Lino',
    expirationDays: null,
  },
  'serpientedemar': {
    icon: require('./../../icons/Peces/serpiente_de_mar_icon.png'),
    name: 'Serpiente De Mar',
    expirationDays: null,
  },
  'serviciodebil': {
    icon: require('./../../icons/Lácteos/servicio_débil_icon.png'),
    name: 'Servicio Débil',
    expirationDays: null,
  },
  'sesamo': {
    icon: require('./../../icons/Frutas Secas/sésamo_icon.png'),
    name: 'Sésamo',
    expirationDays: null,
  },
  'seta': {
    icon: require('./../../icons/Vegetales/seta_icon.png'),
    name: 'Seta',
    expirationDays: null,
  },
  'setavenenosa': {
    icon: require('./../../icons/Variado/seta_venenosa_icon.png'),
    name: 'Seta Venenosa',
    expirationDays: null,
  },
  'skyr': {
    icon: require('./../../icons/Lácteos/skyr_icon.png'),
    name: 'Skyr',
    expirationDays: null,
  },
  'soda': {
    icon: require('./../../icons/Bebidas/soda_icon.png'),
    name: 'Soda',
    expirationDays: null,
  },
  'sodaconhelado': {
    icon: require('./../../icons/Bebidas/soda_con_helado_icon.png'),
    name: 'Soda Con Helado',
    expirationDays: null,
  },
  'soju': {
    icon: require('./../../icons/Bebidas/soju_icon.png'),
    name: 'Soju',
    expirationDays: null,
  },
  'sopa': {
    icon: require('./../../icons/Comidas/sopa_icon.png'),
    name: 'Sopa',
    expirationDays: null,
  },
  'sopacaliente': {
    icon: require('./../../icons/Comidas/sopa_caliente_icon.png'),
    name: 'Sopa Caliente',
    expirationDays: null,
  },
  'suero': {
    icon: require('./../../icons/Lácteos/suero_icon.png'),
    name: 'Suero',
    expirationDays: null,
  },
  'suerodelaleche': {
    icon: require('./../../icons/Lácteos/suero_de_la_leche_icon.png'),
    name: 'Suero De La Leche',
    expirationDays: null,
  },
  'sushi': {
    icon: require('./../../icons/Comidas/sushi_icon.png'),
    name: 'Sushi',
    expirationDays: null,
  },
  'tabladequesos': {
    icon: require('./../../icons/Lácteos/tabla_de_quesos_icon.png'),
    name: 'Tabla De Quesos',
    expirationDays: null,
  },
  'taco': {
    icon: require('./../../icons/Comidas/taco_icon.png'),
    name: 'Taco',
    expirationDays: null,
  },
  'tacos': {
    icon: require('./../../icons/Comidas/tacos_icon.png'),
    name: 'Tacos',
    expirationDays: null,
  },
  'takoyaki': {
    icon: require('./../../icons/Comidas/takoyaki_icon.png'),
    name: 'Takoyaki',
    expirationDays: null,
  },
  'tallarines': {
    icon: require('./../../icons/Comidas/tallarines_icon.png'),
    name: 'Tallarines',
    expirationDays: null,
  },
  'tamarindo': {
    icon: require('./../../icons/Frutas/tamarindo_icon.png'),
    name: 'Tamarindo',
    expirationDays: null,
  },
  'tapas': {
    icon: require('./../../icons/Comidas/tapas_icon.png'),
    name: 'Tapas',
    expirationDays: null,
  },
  'tarrodedulces': {
    icon: require('./../../icons/Dulces/tarro_de_dulces_icon.png'),
    name: 'Tarro De Dulces',
    expirationDays: null,
  },
  'tarrodemiel': {
    icon: require('./../../icons/Dulces/tarro_de_miel_icon.png'),
    name: 'Tarro De Miel',
    expirationDays: null,
  },
  'tarta': {
    icon: require('./../../icons/Comidas/tarta_icon.png'),
    name: 'Tarta',
    expirationDays: null,
  },
  'tartadechocolate': {
    icon: require('./../../icons/Dulces/Tarta_de_chocolate_icon.png'),
    name: 'Tarta De Chocolate',
    expirationDays: null,
  },
  'tazadecafe': {
    icon: require('./../../icons/Bebidas/taza_de_café_icon.png'),
    name: 'Taza De Café',
    expirationDays: null,
  },
  'te': {
    icon: require('./../../icons/Bebidas/té_icon.png'),
    name: 'Té',
    expirationDays: null,
  },
  'tedeburbujas': {
    icon: require('./../../icons/Bebidas/té_de_burbujas_icon.png'),
    name: 'Té De Burbujas',
    expirationDays: null,
  },
  'tedegengibre': {
    icon: require('./../../icons/Bebidas/te_de_gengibre_icon.png'),
    name: 'Te De Gengibre',
    expirationDays: null,
  },
  'tedelaleche': {
    icon: require('./../../icons/Bebidas/té_de_la_leche_icon.png'),
    name: 'Té De La Leche',
    expirationDays: null,
  },
  'tehelado': {
    icon: require('./../../icons/Bebidas/té_helado_icon.png'),
    name: 'Té Helado',
    expirationDays: null,
  },
  'tequila': {
    icon: require('./../../icons/Bebidas/tequila_icon.png'),
    name: 'Tequila',
    expirationDays: null,
  },
  'tetera': {
    icon: require('./../../icons/Bebidas/tetera_icon.png'),
    name: 'Tetera',
    expirationDays: null,
  },
  'tiburon': {
    icon: require('./../../icons/Peces/tiburón_icon.png'),
    name: 'Tiburón',
    expirationDays: null,
  },
  'tiramisu': {
    icon: require('./../../icons/Dulces/tiramisu_icon.png'),
    name: 'Tiramisu',
    expirationDays: null,
  },
  'tocino': {
    icon: require('./../../icons/Carnes/tocino_icon.png'),
    name: 'Tocino',
    expirationDays: null,
  },
  'tofu': {
    icon: require('./../../icons/Comidas/Tofu_icon.png'),
    name: 'Tofu',
    expirationDays: null,
  },
  'tomate': {
    icon: require('./../../icons/Comidas/tomate_icon.png'),
    name: 'Tomate',
    expirationDays: 7,
  },
  'tortas': {
    icon: require('./../../icons/Dulces/tortas_icon.png'),
    name: 'Tortas',
    expirationDays: null,
  },
  'tortilla': {
    icon: require('./../../icons/Comidas/tortilla_icon.png'),
    name: 'Tortilla',
    expirationDays: null,
  },
  'tortita': {
    icon: require('./../../icons/Comidas/tortita_icon.png'),
    name: 'Tortita',
    expirationDays: null,
  },
  'tortuga': {
    icon: require('./../../icons/Peces/tortuga_icon.png'),
    name: 'Tortuga',
    expirationDays: null,
  },
  'tostada': {
    icon: require('./../../icons/Comidas/tostada_icon.png'),
    name: 'Tostada',
    expirationDays: null,
  },
  'tostadasdemantequilla': {
    icon: require('./../../icons/Panes/tostadas_de_mantequilla_icon.png'),
    name: 'Tostadas De Mantequilla',
    expirationDays: null,
  },
  'tostadora': {
    icon: require('./../../icons/Dulces/tostadora_icon.png'),
    name: 'Tostadora',
    expirationDays: null,
  },
  'trigo': {
    icon: require('./../../icons/Dulces/trigo_icon.png'),
    name: 'Trigo',
    expirationDays: null,
  },
  'trufa': {
    icon: require('./../../icons/Dulces/trufa_icon.png'),
    name: 'Trufa',
    expirationDays: null,
  },
  'unpan': {
    icon: require('./../../icons/Comidas/un_pan_icon.png'),
    name: 'Un Pan',
    expirationDays: null,
  },
  'uunijuusto': {
    icon: require('./../../icons/Lácteos/uunijuusto_icon.png'),
    name: 'Uunijuusto',
    expirationDays: null,
  },
  'uva': {
    icon: require('./../../icons/Frutas/uva_icon.png'),
    name: 'Uva',
    expirationDays: null,
  },
  'uvas': {
    icon: require('./../../icons/Comidas/uvas_icon.png'),
    name: 'Uvas',
    expirationDays: null,
  },
  'vainilla': {
    icon: require('./../../icons/Condimentos/vainilla_icon.png'),
    name: 'Vainilla',
    expirationDays: null,
  },
  'vegetal': {
    icon: require('./../../icons/Vegetales/vegetal_icon.png'),
    name: 'Vegetal',
    expirationDays: null,
  },
  'vegetales': {
    icon: require('./../../icons/Comidas/vegetales_icon.png'),
    name: 'Vegetales',
    expirationDays: null,
  },
  'vino': {
    icon: require('./../../icons/Bebidas/vino_icon.png'),
    name: 'Vino',
    expirationDays: null,
  },
  'vla': {
    icon: require('./../../icons/Lácteos/vla_icon.png'),
    name: 'Vla',
    expirationDays: null,
  },
  'vodka': {
    icon: require('./../../icons/Bebidas/vodka_icon.png'),
    name: 'Vodka',
    expirationDays: null,
  },
  'wasabi': {
    icon: require('./../../icons/Vegetales/wasabi_icon.png'),
    name: 'Wasabi',
    expirationDays: null,
  },
  'whisky': {
    icon: require('./../../icons/Bebidas/whisky_icon.png'),
    name: 'Whisky',
    expirationDays: null,
  },
  'yogur': {
    icon: require('./../../icons/Bebidas/yogur_icon.png'),
    name: 'Yogur',
    expirationDays: null,
  },
  'yogurtcongelado': {
    icon: require('./../../icons/Lácteos/yogurt_congelado_icon.png'),
    name: 'Yogurt Congelado',
    expirationDays: null,
  },
  'zalamero': {
    icon: require('./../../icons/Bebidas/zalamero_icon.png'),
    name: 'Zalamero',
    expirationDays: null,
  },
  'zanahoria': {
    icon: require('./../../icons/Condimentos/zanahoria_icon.png'),
    name: 'Zanahoria',
    expirationDays: 20,
  },
  'zapallitoitaliano': {
    icon: require('./../../icons/Vegetales/zapallito_italiano_icon.png'),
    name: 'Zapallito Italiano',
    expirationDays: null,
  },
  'zumodefrutas': {
    icon: require('./../../icons/Bebidas/zumo_de_frutas_icon.png'),
    name: 'Zumo De Frutas',
    expirationDays: null,
  },
  'zumodenaranja': {
    icon: require('./../../icons/Bebidas/zumo_de_naranja_icon.png'),
    name: 'Zumo De Naranja',
    expirationDays: null,
  },
};

export const foodIcons = Object.fromEntries(
  Object.entries(foodData).map(([k, v]) => [k, v.icon])
);

export const categories = {
  'bebidas': {
    icon: require('./../../icons/Categorias/Bebidas.png'),
    name: 'Bebidas',
    items: ['agua', 'aguamineral', 'arcoiris', 'ayran', 'batidordecocteles', 'beber', 'bebidadecoco', 'bebidaenergetica', 'bebidassinalcohol', 'bloodymary', 'borbon', 'cafe', 'cafehelado', 'cafeturco', 'cajadejugo', 'cajadeleche', 'capuchino', 'cerveza', 'champan', 'chocolatecaliente', 'coco', 'coctel', 'cosmopolita', 'dalgona', 'frape', 'horchata', 'infusion', 'jugo', 'kombucha', 'lattemacchiato', 'leche', 'lecheconchocolate', 'lechedefresa', 'licordehierbas', 'licorera', 'limonada', 'malteada', 'margarita', 'martini', 'matcha', 'mimosa', 'mochaccino', 'mojito', 'motivo', 'pinacolada', 'punetazo', 'ramune', 'reajustesalarial', 'refresco', 'ron', 'sangria', 'soda', 'sodaconhelado', 'soju', 'tazadecafe', 'te', 'tedeburbujas', 'tedegengibre', 'tedelaleche', 'tehelado', 'tequila', 'tetera', 'vino', 'vodka', 'whisky', 'yogur', 'zalamero', 'zumodefrutas', 'zumodenaranja'],
  },
  'carnes': {
    icon: require('./../../icons/Categorias/Carnes.png'),
    name: 'Carnes',
    items: ['albondigas', 'alitadepollo', 'alitasdepollo', 'asado', 'bife', 'bistec', 'calendario', 'carne', 'carnedecordero', 'carnedevaca', 'carnemolida', 'carniceria', 'cerdo', 'chuleta', 'cordero', 'costillas', 'embutido', 'filete', 'hamburguesa', 'higado', 'jamon', 'pechugadepollo', 'pegar', 'piernadepollo', 'piernasdepollo', 'pollo', 'polloentero', 'res', 'rinon', 'salami', 'salchicha', 'salchichas', 'tocino'],
  },
  'cereales': {
    icon: require('./../../icons/Categorias/Cereales.png'),
    name: 'Cereales',
    items: ['cereal'],
  },
  'comidas': {
    icon: require('./../../icons/Categorias/Comidas.png'),
    name: 'Comidas',
    items: ['aceitedeoliva', 'albondigas', 'alcachofa', 'almendra', 'arroz', 'barbacoa', 'batidos', 'berenjena', 'bocadillo', 'brocheta', 'brocoli', 'burrito', 'cafe', 'camaron', 'cangrejo', 'cannoli', 'caramelo', 'carne', 'carnedevaca', 'cebolla', 'cena', 'cerdo', 'cereales', 'cerveza', 'champan', 'chocolate', 'chupete', 'coctel', 'col', 'comida', 'comidaindia', 'comidajaponesa', 'cono', 'cordero', 'cosecha', 'costillas', 'crepe', 'cuerno', 'dosa', 'dulce', 'empanadillas', 'emparedado', 'ensalada', 'espaguetis', 'esparrago', 'estofado', 'filete', 'fruta', 'frutas', 'galletas', 'galletasalada', 'gamba', 'gelatina', 'gofre', 'guacamole', 'hamburguesa', 'helado', 'hervido', 'hongos', 'hotdog', 'huevo', 'huevos', 'huevosfritos', 'hummus', 'indio', 'jamon', 'kofta', 'laddu', 'langosta', 'lasmanzanas', 'lata', 'leche', 'lechedealmendras', 'licuadora', 'limon', 'limonada', 'lostomates', 'macarron', 'macedonia', 'magdalena', 'masalapapad', 'mayonesa', 'mazorca', 'mollete', 'nachos', 'naranjas', 'nueces', 'onigiri', 'ostra', 'palomitasdemaiz', 'pan', 'pancho', 'pandemolde', 'panqueques', 'papasfritas', 'papaya', 'parilla', 'pasta', 'pastel', 'pasteleria', 'patatas', 'pepperoni', 'peras', 'pescado', 'pez', 'piernadejamon', 'piernadepollo', 'pimienta', 'pina', 'pizza', 'poder', 'pollo', 'polloasado', 'pomelo', 'pudin', 'puredepatatas', 'queso', 'quesocheddar', 'ramen', 'rebanadadepizza', 'rollodesushi', 'rosquilla', 'salami', 'salchicha', 'salchichas', 'salmon', 'salsadetomate', 'samosa', 'sandia', 'soda', 'sopa', 'sopacaliente', 'sushi', 'taco', 'tacos', 'takoyaki', 'tallarines', 'tapas', 'tarta', 'te', 'tocino', 'tofu', 'tomate', 'tortilla', 'tortita', 'tostada', 'unpan', 'uvas', 'vegetales', 'vino', 'zalamero'],
  },
  'condimentos': {
    icon: require('./../../icons/Categorias/Condimentos.png'),
    name: 'Condimentos',
    items: ['aceitevegetal', 'ajo', 'albahaca', 'alcaravea', 'anis', 'azafran', 'azucar', 'bayadeespino', 'bayas', 'berbero', 'berro', 'cal', 'camaron', 'canela', 'cardamomo', 'cebolla', 'cebollaverde', 'chile', 'cilantro', 'clavo', 'eneldo', 'enescabeche', 'esparragos', 'hinojo', 'hojas', 'jengibre', 'lahierbadelimon', 'lechedecoco', 'limon', 'manteca', 'menta', 'mermeladadefresa', 'miel', 'mieldemaple', 'mostaza', 'nuezmoscada', 'papa', 'pimientomorron', 'pimientopicante', 'queso', 'romero', 'rucula', 'sal', 'salsa', 'salsadechile', 'salsadetomate', 'salvia', 'sopa', 'vainilla', 'yogur', 'zanahoria'],
  },
  'dulces': {
    icon: require('./../../icons/Categorias/Dulces.png'),
    name: 'Dulces',
    items: ['algodondeazucar', 'anillopop', 'arcoiris', 'barradechocolate', 'bastondecaramelo', 'bolasdechoco', 'brocheta', 'cacao', 'caramelo', 'carino', 'cena', 'chicle', 'chicles', 'chocolate', 'chocolatecaliente', 'chupete', 'churros', 'crepe', 'croissant', 'cuerno', 'cupcake', 'donas', 'dulce', 'dulceria', 'dulces', 'eclair', 'emparedado', 'equilibrar', 'fondue', 'fresa', 'frijolitosconfitados', 'galleta', 'galletas', 'galletasalada', 'gelatina', 'glaciar', 'gofre', 'gominola', 'gragea', 'hamburguesa', 'helado', 'heladoconfrutasynueces', 'hombredepandejengibre', 'huevodechocolate', 'lactoso', 'macaron', 'macarones', 'macarons', 'magdalena', 'malvavisco', 'malvaviscos', 'mantecadecacahuete', 'manzanacaramelizada', 'maquinadedulces', 'mermelada', 'miel', 'mollete', 'naranja', 'oblea', 'ositodegoma', 'osodegominola', 'paletadehielo', 'palitodepaleta', 'palodedulce', 'palodehelado', 'panal', 'pannacotta', 'panqueques', 'pastel', 'pasteldecumpleanos', 'pasteldefresa', 'pastelderollo', 'pasteldezanahoria', 'patatasfritas', 'piedemanzana', 'piruleta', 'piruli', 'pizza', 'pudin', 'regaliz', 'rodillo', 'rollodecanela', 'rosquilla', 'sandwichdehelado', 'taco', 'tarrodedulces', 'tarrodemiel', 'tarta', 'tartadechocolate', 'tedeburbujas', 'tiramisu', 'tortas', 'tortita', 'tostadora', 'trigo', 'trufa', 'unpan', 'zalamero'],
  },
  'frutas': {
    icon: require('./../../icons/Categorias/Frutas.png'),
    name: 'Frutas',
    items: ['cereza', 'coco', 'dragondefruta', 'frambuesa', 'fresa', 'fruta', 'frutaestrella', 'goji', 'granada', 'higo', 'kiwi', 'lima', 'limon', 'lychee', 'mango', 'manzana', 'manzanarosa', 'maracuya', 'melocoton', 'melon', 'membrillo', 'naranja', 'papaya', 'pera', 'pina', 'platano', 'sandia', 'tamarindo', 'uva'],
  },
  'frutassecas': {
    icon: require('./../../icons/Categorias/Frutas Secas.png'),
    name: 'Frutas Secas',
    items: ['almendra', 'avellana', 'bellota', 'cacao', 'cardamomo', 'castana', 'coco', 'conodepino', 'granosdecafe', 'macadamia', 'mani', 'nuecesdebrasil', 'nuez', 'nuezmoscada', 'pacana', 'pistacho', 'semilladecalabaza', 'semilladegirasol', 'semilladelino', 'sesamo'],
  },
  'lacteos': {
    icon: require('./../../icons/Categorias/Lácteos.png'),
    name: 'Lácteos',
    items: ['ayran', 'ccreaagria', 'cremabatida', 'cremafresca', 'cuajada', 'cuarc', 'dadia', 'dangke', 'dulcedeleche', 'ghee', 'helado', 'kefir', 'kulfi', 'lassi', 'leche', 'lechecondensada', 'lechedecamello', 'lechedeoveja', 'lecheenpolvo', 'manteca', 'nata', 'pudin', 'queso', 'quesoedam', 'quesomozzarella', 'quesosuizo', 'requeson', 'ricotta', 'serviciodebil', 'skyr', 'suero', 'suerodelaleche', 'tabladequesos', 'uunijuusto', 'vla', 'yogur', 'yogurtcongelado'],
  },
  'legumbres': {
    icon: require('./../../icons/Categorias/Legumbres.png'),
    name: 'Legumbres',
    items: ['anacardo', 'chia', 'edamame', 'frijoles', 'frijolesrojos', 'garbanzos', 'guisantes', 'habadesoja', 'judiasverdes', 'lentejas', 'maiz'],
  },
  'panes': {
    icon: require('./../../icons/Categorias/Panes.png'),
    name: 'Panes',
    items: ['bollo', 'cesta', 'crepe', 'cuerno', 'descanso', 'emparedado', 'galleta', 'galletas', 'galletasalada', 'granos', 'harina', 'helado', 'hornomicroondas', 'huevos', 'junquillo', 'leche', 'macarons', 'magdalena', 'masa', 'miel', 'mollete', 'pan', 'panintegral', 'pastel', 'queso', 'rebanadoradepan', 'rosquilla', 'tarta', 'tostadasdemantequilla'],
  },
  'peces': {
    icon: require('./../../icons/Categorias/Peces.png'),
    name: 'Peces',
    items: ['algasmarinas', 'anemonademar', 'angelote', 'anguila', 'atun', 'bacalao', 'ballena', 'banco', 'burbujas', 'caballodemar', 'calamar', 'camaron', 'cangrejo', 'cangrejoermitano', 'cascara', 'concha', 'coral', 'delfin', 'erizodemar', 'espina', 'estrellademar', 'foca', 'gaviota', 'idolomoro', 'langosta', 'medusa', 'mejillon', 'orca', 'pez', 'pezcirujano', 'pezespada', 'pezglobo', 'pezluna', 'pezmartillo', 'pezpayaso', 'pezvolador', 'pinguino', 'pulpo', 'rape', 'rayo', 'salmon', 'sardina', 'serpientedemar', 'tiburon', 'tortuga'],
  },
  'sandwich': {
    icon: require('./../../icons/Categorias/Sandwich.png'),
    name: 'Sandwich',
    items: ['burrito', 'cuerno', 'emparedado', 'hamburguesa', 'hamburguesaconqueso', 'pancho', 'sandwich', 'sandwichdehamburguesa', 'sandwichdehotdog', 'taco', 'tostada', 'unpan'],
  },
  'variado': {
    icon: require('./../../icons/Categorias/Variado.png'),
    name: 'Variado',
    items: ['arce', 'bebidacaliente', 'conodepino', 'hoja', 'hojadearce', 'hojaderoble', 'linterna', 'madera', 'oso', 'pajaro', 'puercoespin', 'rama', 'setavenenosa'],
  },
  'vegetales': {
    icon: require('./../../icons/Categorias/Vegetales.png'),
    name: 'Vegetales',
    items: ['aceituna', 'acelga', 'agave', 'aguacate', 'ajipicante', 'ajo', 'alcachofa', 'apio', 'bambu', 'batata', 'berenjenas', 'brocoli', 'calabaza', 'cebolla', 'cebollin', 'chalote', 'coliflor', 'colrizada', 'durian', 'esparragos', 'espinacas', 'frijoles', 'hierba', 'hinojo', 'jengibre', 'lechuga', 'maiz', 'mangostan', 'mani', 'nabo', 'natillasappel', 'nuez', 'pacana', 'palmeradatilera', 'patatas', 'pepino', 'physalis', 'pimienta', 'puerro', 'rabano', 'remolacha', 'repollo', 'repollorojo', 'seta', 'tomate', 'trigo', 'vegetal', 'wasabi', 'zanahoria', 'zapallitoitaliano'],
  },
};

export function normalizeFoodName(name) {
  return name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, '');
}

export function getFoodInfo(name) {
  return foodData[normalizeFoodName(name)];
}

export function getFoodIcon(name) {
  const info = getFoodInfo(name);
  return info ? info.icon : undefined;
}

export function getFoodCategory(name) {
  const normalized = normalizeFoodName(name);
  for (const [cat, data] of Object.entries(categories)) {
    if (data.items.includes(normalized)) {
      return cat;
    }
  }
  return null;
}

export default foodIcons;